### ISSUE TITLE
[horizontal] labelled list not working in pdf output

### ISSUE THREAD

**Issue by marceloverdijk** [asciidoctor/asciidoctor#1722] opened 2016-04-09 22:20 UTC
E.g having:

```
[horizontal]
CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.
```

outputs label and content on the same line for html, but not for pdf.

**Comment by mojavelinux** [comment] 2016-04-09 22:42
You are correct, this is not yet implemented. Since this is a duplicate of https://github.com/asciidoctor/asciidoctor-pdf/issues/310 I'm going to close this one and link to that one.

**Closed** 2016-04-09 22:42 UTC
Labels: duplicate
