### ISSUE TITLE
New Backend for Plain Text

### ISSUE THREAD

**Issue by fwilhe** [asciidoctor/asciidoctor#1636] opened 2015-12-28 08:45 UTC
I would like to have a backend, that produces plain text. "Why, your input is plain text already", you might ask.

Consider this demo document:

```
= Demo Document

== Enumeration

. a
. b
. c

== Lorem

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod.
Tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
At vero eos et accusam et justo duo dolores et ea rebum.

Lorem ipsum dolor sit amet, consetetur sadipscing elitr.
Sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat.
Sed diam voluptua, at vero eos et accusam et.
```

When reading this, I would expect the enumeration to be explicit, but as author, I don't want to write it out. Also I would not want every sentence to start at a new line, but rather expect the lines to be joined as they are in other outputs of asciidoctor.

I am not sure what other features of the language this touches.

Any opinions on this issue?

**Comment by ds26gte** [comment] 2015-12-28 15:22
There are already at least two existing ways to secure what you want.

1. Convert to HTML using Asciidoctor, and then call `lynx -dump` on the result.

2. Convert to manpage using Asciidoctor, and then redirect `man` of the result into a file (instead of paging it).

Both methods are easily abstractable into a shell script.

**Comment by jxxcarlson** [comment] 2015-12-28 17:01
In the same vein, I would like a backend that reproduces the input asciidoctor text.

This may seem strange, but it comes up in manipulating the text via a suitable 
editor, e.g, permuting the order of sections; parse the document, then
output the original asciidoc text with sections in a different order.

**Comment by fwilhe** [comment] 2015-12-28 17:34
Hello @ds26gte,

thanks for your suggestions. I tried both of them, the manpage did not work, not sure what the problem is. Converting the html via lynx kinda works, but does not provide the output I would like to see.

* Markup (such as headings) is lost, which I do not want. I want the output still to be an Asciidoc file
* It has a fixed line width, I would prefer lines to be as long as the paragraphs are and let the user's editor/viewer decide where to break

Would you see any reason to reject a PR that adds such a converter?

**Comment by ds26gte** [comment] 2015-12-28 18:59
@fwilhe, yes, sorry, I forgot that the manpage's source document is required by Asciidoctor to be in a certain format, otherwise it simply won't convert.

There isn't an overwhelming need why Asciidoctor requires this, though. There should be ways to supply default name (could be basename of document file), volume (could be 1), and purpose (could be some inoffensive generic text), if these aren't already supplied in the rigorous form that Asciidoctor expects. It is mildly irksome that a document should fail the `manpage` backend while being OK with other backends.

Actually, it is @mojavelinux's decision to make about accepting a PR for this. I do think text-editor macros that you can fine-tune to your preferences are the way to go (even if you want to keep around two separate documents for the same content). Any formatting decision that a potential `asciidoctor` backend would make is likely to elicit multiple contradicting critiques. By its very nature, it can't please all.

**Comment by mojavelinux** [comment] 2015-12-29 02:20
I think this would make a great extension (i.e., custom converter), but I don't believe it belongs in core. There are also many different definitions of "plain text", which even further justifies why it would be handle in an (optional) extension with a specific output in mind.

The a2x command from AsciiDoc Python uses lynx to generate plain text as @ds26gte suggested. However, I much prefer the output of w3m.

    $ w3m -dump -cols 2147483647 sample.html > sample.txt

Notice that you can set the number of columns so that lines aren't hard wrapped at a fixed line width (adjust to the maximum length of your lines). The upper bounds seems to be MAX_INT (2147483647). (which you can retrieve dynamically using `perl -MPOSIX -e 'print INT_MAX'`).

It doesn't seem to be possible to configure w3m to preserve/insert markup that indicates headings. However, I'm sure there are other tools that can do this.

You could hook `w3m -dump` into the Asciidoctor invocation using a Postprocesser extension. If you wanted more customized output, then you'd move to a converter.

> @ds26gte: There isn't an overwhelming need why Asciidoctor requires this, though. ... It is mildly irksome that a document should fail the manpage backend while being OK with other backends.

The reason is really just historical. I duplicated the logic in AsciiDoc Python, not having a lot of knowledge of manpages (which I understand much better now). If there's a way to make all that optional and still produce a valid manpage, I'm all for it. Let's track that in a separate issue.

> @jxxcarlson: I would like a backend that reproduces the input asciidoctor text.

This is possible by chaining docbookrx into the pipeline. Convert to DocBook, then use [docbookrx](https://github.com/opendevise/docbookrx) to convert back to AsciiDoc.

Obviously, it would be nice to cut out the middleman, but that at least gives you something in the interim.

The same suggestion I gave for the plain text converter also applies here. Just create a custom converter that produces AsciiDoc. It's possible today...it just takes some work. (very similar, in fact, to the [manpage converter](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/manpage.rb)). Here's a rough prototype I started (using the template converter): https://github.com/mojavelinux/asciidoctor-backends/tree/to-asciidoc/erb/asciidoc

**Comment by mojavelinux** [comment] 2015-12-29 02:28
You might also try html-to-text from npm.

https://www.npmjs.com/package/html-to-text

That gives special treatments to headings, which I'm sure you can then hack. (I was able to make a simple change to add a leading '#').

**Comment by ds26gte** [comment] 2016-01-03 23:25
Part of the reason for wanting an `asciidoctor` backend seems to be the tension between wanting sentences to start on their own lines for editability and also wanting them flowed for readability. The tension is of course because it is not possible to have both styles in the same physical file. 

I wonder about the continued relevance of the sentence-per-line technique. It’s a practice that originated in the era of line editors. See, e.g., the early 1970s text by Kernighan, [Unix for Beginners](http://www.mtholyoke.edu/~mcrowley/beginners.pdf), where the practice is encouraged because it makes edits easy when composing `troff` in `ed`, both of which are line-oriented. The first “visual” (i.e., not “line”) editors, `vi` and `emacs`, wouldn’t show up until 1976.

Sentence-per-line was no doubt a good compromise to secure editable prose given the tools available at the time. Nowadays however, modern text editors have made changing, deleting, and shuffling sentences as bona-fide text objects so much easier.

**Comment by mojavelinux** [comment] 2016-01-04 00:32
> sentences to start on their own lines for editability and also wanting them flowed for readability.

The reader never sees the line breaks because they are folded either by the renderer (HTML) or the converter (Asciidoctor PDF). And it's fairly easy to fold the input lines, as we have done for Asciidoctor PDF). There's no need to rewrite the AsciiDoc source just for that.

> modern text editors have made changing, deleting, and shuffling sentences as bona-fide text objects so much easier.

I don't share this opinion. I still see modern text editors struggling with the sentence structure (they still see paragraphs as blobs of text).

Sentence-per-line fundamentally changed how I write (which I talk about in my presentation about writing, see https://www.youtube.com/watch?v=r6RXRi5pBXg) and there's no way I would write any other way now. I think it's perfectly suited for writing prose.

**Comment by fwilhe** [comment] 2016-01-04 19:54
@mojavelinux your talk is the reason why I started doing this, and therefore why I created this issue. I do completely agree with you on that.

I agree that my definition of "plain text" is just one of possibly infinite, so I agree that this is not something for the "core" of asciidoctor.

Thanks for all the workaround hints, I will investigate them to see what fits best. And I might tackle the custom-converter task.

From my point of view, this discussion is over. Should we close the issue, or leave it open to be closed by an implementation of a custom converter?

**Comment by mojavelinux** [comment] 2016-01-05 03:30
:+1: 

You'll open up a world of possibilities once you get into making custom converters. In fact, I bet you'll find new utility in AsciiDoc. Add extensions on to that and you can almost get it to make anything you want. (I think Asciidoctor PDF is a pretty great example of this).

We can close the issue, but it doesn't mean we're going anywhere. We'll still be around to discuss and guide you on your journey.

**Closed by mojavelinux** 2016-01-05 03:30 UTC

**Comment by tajmone** [comment] 2018-10-15 22:42
@mojavelinux:

> You might also try html-to-text from npm.
> 
> https://www.npmjs.com/package/html-to-text

Thanks for the tip! That's a great tool indeed and I've managed to get good results just by tweaking the Asciidoctor CLI option and using [html-to-text-cli] via CLI, with some options.

I've published a Gist with a practical example (for a project I'm working on), contaning a sample batch (public domain) and two palintext results preview of AsciiDoc converted docs:

- [`adoc2txt.bat`][adoc2txt.bat] — a sample batch that converts Highlight's `README.adoc` and `ChangeLog.adoc` to HTML and then to txt.
- [`README.txt`][README.txt] — preview of final result.
- [`ChangeLog.txt`][ChangeLog.txt] — preview of final result.

The batch script is dead simple:

```batch
CALL :conv2txt README.adoc
CALL :conv2txt ChangeLog.adoc

EXIT /B

:conv2txt
CALL asciidoctor^
    -a sectids!^
    -a sectanchors!^
    %1

TYPE %~n1.html | html-to-text^
    --wordwrap=70^
    --hideLinkHrefIfSameAsText=true^
    --ignoreHref=true^
    --unorderedListItemPrefix=" + "^
    > %~n1.txt

EXIT /B
```

But of course, using JS instead of CLI will allow even finer grain control, by adding custom functions to process HTML tags (as @mojavelinux mentioned).

Just thought to share the script and examples, in case someone needs to get going with it.

Tristano



[adoc2txt.bat]: https://gist.github.com/tajmone/14cba70b583b971a1c0772bd4213dc07#file-adoc2txt-bat
[README.txt]: https://gist.github.com/tajmone/14cba70b583b971a1c0772bd4213dc07#file-readme-txt
[ChangeLog.txt]: https://gist.github.com/tajmone/14cba70b583b971a1c0772bd4213dc07#file-changelog-txt

[html-to-text-cli]: https://www.npmjs.com/package/html-to-text-cli

[Issue #1636]: https://github.com/asciidoctor/asciidoctor/issues/1636#issuecomment-167702398

**Comment by angolini** [comment] 2019-01-09 17:48
I'm only adding my example. Just in case someone from the future end up in this page.

I have a complex asciidoc source code, and I include sections and tables depending on variables, some piece of text are variables values.

So, for me it's pretty easy to "understand my code", however, I need to share the plain text to another team and I'm looking for a way to avoid PDF (binary) and also avoid HTML (because it's noise for them), so I'm thought about a plain text backend, because I would have the final text instead of my complex variable net, in a pure text shape. It could be a asciidoc text shape, but with the dependencies and variables evaluated.

Thanks
(I'm sorry, I wish I could add this without notifying anyone)

**Comment by davidgilbertson** [comment] 2024-08-26 05:05
I'm just going to throw in my use case too. I have text in asciidoc that I want to make searchable (for a RAG application to allow querying the content with a chatbot), so don't want anything you wouldn't read out to someone (formatting markers, etc). I was surprised to find out that this isn't a simple option. I understand there's non-obvious cases like "what to do with tables" and "what abou image titles" but still, it seems like being able to strip out just the words shouldn't require multiple tools and bash scripts.

For context, I'm processing this in Python, so writing back out to a file and using a bash script adds quite a bit of complexity. My workaround is to first go to HTML, then to extract text from that.
