### ISSUE TITLE
Potential regression on tag inclusion in 1.5.6.1

### ISSUE THREAD

**Issue by cexbrayat** [asciidoctor/asciidoctor#2369] opened 2017-08-15 16:15 UTC
Previously, using `1.5.5`, we could do something like:

```asciidoc
= Hello, AsciiDoc!
include::include.ts[tags=h1]
```

with `include.ts` looking like:

```typescript
const template = `
<body>
  <!-- tag::h1[] -->
  <h1>Hello</h1>
  <!-- end::h1[] -->
</body>`;
```

which was producing the expected result:
<img width="404" alt="capture d ecran 2017-08-15 a 18 14 04" src="https://user-images.githubusercontent.com/411874/29324774-9e9bd6da-81e5-11e7-851f-5d68fc9a9eab.png">

Upgrading to `1.5.6.1` leads to the following error:

```
asciidoctor: WARNING: issue.adoc: line 2: tag 'h1' not found in include file: /Users/cedric/Code/tests/ascidoctor-tag-issue/include.ts
```

and the HTML is no longer displayed.

This is a minimal reproduction, but I've seen it on every project I tried to bump to the latest release.

**Comment by Mogztter** [comment] 2017-08-15 21:31
This commit may be the cause of this regression: https://github.com/asciidoctor/asciidoctor/commit/10f6b096d545e1294f99d4fde2b9d6bbee75d3ec
Could you please try to change the file extension to `.html` ?

Since`CIRCUMFIX_COMMENTS` can't be configured, I think we will have to add the `.ts` file extension:

```diff
-['<!--', '-->'] => ['.html', '.xhtml', '.xml', '.xsl']
+['<!--', '-->'] => ['.html', '.xhtml', '.xml', '.xsl', '.ts']
```

@mojavelinux Maybe we should allow users to configure the comment prefix/suffix for their favorite language ?

```adoc
include::include.ts[tags=h1,prefix=<!--,suffix=-->]
```

I can't find a consistent syntax to pass this information via attributes (because attributes are only `'key' => 'value'` and in this case we need to defined an `Hash`):

```js
custom_circumfix_comments: [{
  prefix: '<!--', 
  suffix: '-->',
  file_extensions: ['.ts']
}]
```

**Comment by mojavelinux** [comment] 2017-08-15 21:55
@Mogztter correctly points out that this is a feature, not a bug.

However, I hadn't thought about the case of the tag being used in a string inside a file which has different comments. The idea behind the enhancement is to not eat comments it shouldn't eat. So it's hard to know how we would handle that.

I'm inclined to make the case that using tags this way isn't really correct. But I need to give it some more thought.

> @mojavelinux Maybe we should allow users to configure the comment prefix/suffix for their favorite language?

I really don't like that type of coupling. It makes the AsciiDoc way too low level.

**Comment by mojavelinux** [comment] 2017-08-15 21:58
> Since CIRCUMFIX_COMMENTS can't be configured, I think we will have to add the .ts file extension:

This would not be the correct solution because it would cause other tags to stop working. The ts extension is for TypeScript, which has normal line comments.

But if a new extension did need to be added, that constant can be configured. You just have to assign a new value to the Hash.

```
CIRCUMFIX_COMMENTS['xslt'] = { prefix: "<!--", suffix: "-->" }
```

**Comment by mojavelinux** [comment] 2017-08-15 22:03
Actually, nevermind, it does work to customize this Hash for this case.

```
Asciidoctor::CIRCUMFIX_COMMENTS['.ts'] = { prefix: "<!--", suffix: "-->" }
```

Just put that in a Ruby file and load it when you invoke Asciidoctor.

**Comment by cexbrayat** [comment] 2017-08-16 07:54
@Mogztter @mojavelinux Thank you for taking the time to dig into this.

I understand that this usage might seem far fetched :) But nowadays most JS frameworks have blurry lines between HTML/JS/TS/CSS, so it's fairly common for us to have HTML comments in a string in a JS/TS file.

The workaround indeed works while waiting for a more friendly solution. 👍

**Comment by mojavelinux** [comment] 2017-08-16 08:08
We could certainly add .js and .ts to the circumfix comment table (under the XML-style comment entry). We don't have to worry about that breaking something since that is how it worked before. In 1.5.6, we just reduced where the circumfix comments were being truncated.

This is a really tricky problem since strings in code can contain the source of any other language, and there's no way we would know that. We don't just search for the tag anywhere in a line since that is a very expensive check...and potentially matches stuff it shouldn't. So I'm a bit perplexed about how to handle this (beyond .js and .ts).

**Comment by mojavelinux** [comment] 2017-08-16 08:09
(though I may be trying to be too conservative here).

**Comment by mojavelinux** [comment] 2017-08-17 05:40
I've submitted a proposal that restores the old behavior.

https://github.com/asciidoctor/asciidoctor/pull/2371

The caveat is that if you had a string containing CSS in the JavaScript, you could not put tags in comments. The current logic only supports one set of circumfix comments...and we've chosen the XML dialect here.

**Comment by akosma** [comment] 2017-09-26 11:06
I inadvertently posted a duplicate of this one in #2430. Is there a way to solve this issue? In my case the problem is that I'm trying to reference a tag inside an Apple Property List file – which is actually XML.

**Comment by mojavelinux** [comment] 2018-04-13 20:47
After giving this more thought, what I've come to realize is that the file extension is not a reliable indicator of the contents (putting aside the fact that we don't want to have to maintain a file extension list). The contents can have a mix of languages, either because the language supports it or because the language is embedded inside a multi-line string.

A better way to approach is to look for lines that have a trailing circumfix comment delimiter, then validate that its pair is present earlier in the line. That way, we're sure we've identified a line with a circumfix comment. Then we proceed to strip the trailing delimiter and look for a tag at the end of the line. This is both efficient and solves the problem at hand (and we no longer have to maintain a list of file extensions).

**Comment by mojavelinux** [comment] 2018-04-20 23:45
I tried many different strategies. Due to the fact that we have to consider tags that fall inside of circumfix (or even block) comments, there's no use in enforcing or even checking that the tag appears at the end of the line.

My tests have shown that the most efficient way to find tags is as follows:

* check if line includes double colon
* then check if line includes double square bracket
* then run the tag directive regular expression on the line

Here are the rules enforced by the regular expression:

* The tag must either start at the beginning of the line or be preceded by a word boundary
* The tag must either end at the end of the line or be followed by a space

Even though we allow any non-word character to be to the left of the tag, it should be a space unless the tag starts at the beginning of the line. That's the rule we should continue to document.

This change address this regression and many other cases.

**Closed** 2018-04-21 01:12 UTC
Labels: bug, wip
