### ISSUE TITLE
Please, update Mathjax to 3.X version

### ISSUE THREAD

**Issue by sindzicat** [asciidoctor/asciidoctor#3729] opened 2020-08-08 10:38 UTC
Please, update Mathjax to 3.X version. It will work much more faster.

Best regards,
Andrey.

**Comment by mojavelinux** [comment] 2020-08-08 11:19
Duplicate of #3449. Please comment there.

**Closed by mojavelinux** 2020-08-08 11:19 UTC

**Comment by sindzicat** [comment] 2020-08-08 11:46
Oops, I tried to search before, but I really didn't see this issue. Sorry for this.
