### ISSUE TITLE
How to embed PDF in same pane in asciidoc

### ISSUE THREAD

**Issue by slowGetter** [asciidoctor/asciidoctor#3960] opened 2021-03-05 12:59 UTC
Hi,

I need to embed pdf in the same window as in other table of content.
I used the https://docs.antora.org/antora/2.2/asciidoc/link-attachment/  It only creates a link and when I click on it, pdf is  opens as a new link which is external to site. But I want it to be in same window.. so that I can use table of content. 
Is there any other way to achieve it.

**Comment by mojavelinux** [comment] 2021-03-05 20:17
This is a reasonable request, though a duplicate of #3908. You can find discussion in that issue about it.

**Closed by mojavelinux** 2021-03-05 20:17 UTC
