### ISSUE TITLE
Problem with asciidoctor-bibtex after update to asciidoctor 2.0.2

### ISSUE THREAD

**Issue by pela9** [asciidoctor/asciidoctor#3215] opened 2019-03-27 14:16 UTC
Version 2.0.2 fixed the previous problem with the asciidoctor-bibtex extension. Now there is a new  problem for some inputs. I have reported this also at the asciidoctor-bibtex archive. The stack trace I get when running with asciidoctor --trace is:

```
RUBYLIB=/home/pela/svnroot/internal-tools/asciidoc-templates/db2ltx \
        asciidoctor -a docinfo=shared,private -a templatesdir=/home/pela/svnroot/internal-tools/asciidoc-templates -r asciidoctor-diagram -a blockdiag=/usr/bin/blockdiag -a dot=/usr/bin/dot -r asciidoctor-bibtex --verbose --trace  -b docbook -o makeguide.xml makeguide.adoc
/home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:113:in `gsub!': asciidoctor: FAILED: /home/pela/svnroot/QAG/dcs-make/makeguide.adoc: Failed to load AsciiDoc document - can't modify frozen String (RuntimeError)
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:113:in `block (2 levels) in process'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:112:in `each'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:112:in `block in process'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:109:in `each'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:109:in `process'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor/document.rb:557:in `[]'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor/document.rb:557:in `block in parse'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor/document.rb:556:in `each'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor/document.rb:556:in `parse'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor.rb:1301:in `load'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor.rb:1410:in `convert'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor.rb:1518:in `block in convert_file'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor.rb:1518:in `open'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor.rb:1518:in `convert_file'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor/cli/invoker.rb:126:in `block in invoke!'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor/cli/invoker.rb:109:in `each'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor/cli/invoker.rb:109:in `invoke!'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/bin/asciidoctor:15:in `<top (required)>'
        from /home/pela/bin/asciidoctor:23:in `load'
        from /home/pela/bin/asciidoctor:23:in `<main>'
```

**Comment by Mogztter** [comment] 2019-03-27 15:00
I think this issue should be fixed in the asciidoctor-bibtex extension by replacing `text.gsub!(...)` with `text = text.gsub(...)`.
I will also allow the extension to be transpile in JavaScript with Opal as String are immutables.

**Comment by Mogztter** [comment] 2019-03-27 15:05
One a side note, could you please modify the content of your issue to format the stack trace as a literal block (using three back ticks):

```
RUBYLIB=/home/pela/svnroot/internal-tools/asciidoc-templates/db2ltx 
asciidoctor -a docinfo=shared,private -a templatesdir=/home/pela/svnroot/internal-tools/asciidoc-templates -r asciidoctor-diagram -a blockdiag=/usr/bin/blockdiag -a dot=/usr/bin/dot -r asciidoctor-bibtex --verbose --trace -b docbook -o makeguide.xml makeguide.adoc
```
```
/home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:113:in gsub!': asciidoctor: FAILED: /home/pela/svnroot/QAG/dcs-make/makeguide.adoc: Failed to load AsciiDoc document - can't modify frozen String (RuntimeError) 
  from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:113:in block (2 levels) in process'
  from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:112:in each' from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:112:in block in process'
```

It will be easier to read, thanks :wink:

**Comment by mojavelinux** [comment] 2019-03-28 01:23
The switch from `gsub!` to `gsub` (and frozen string literals) is a feature, not a bug. This will require an update to the asciidoctor-bibtex extension.

In fact, `gsub!` and string manipulation should never be used. It's bad practice and makes the extension non-portable. The only reason it was used in Asciidoctor core was for raw speed, but we have since determined that even that is a fallacy.

**Comment by mojavelinux** [comment] 2019-03-28 01:24
This is an upstream issue, so we will deal with it there. https://github.com/asciidoctor/asciidoctor-bibtex/issues/38

**Closed by mojavelinux** 2019-03-28 01:24 UTC
