### ISSUE TITLE
Include multiple files in a directory using globbing

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor#2410] opened 2017-09-12 20:08 UTC
I have a document that is laid out in several chapters in a directory. I want to include all documents in the final HTML/PDF.

Sphinx allows to include multiple files in a directory, see http://www.sphinx-doc.org/en/stable/markup/toctree.html for details. 

This would allow me to number the chapters in a directory and just include all of them without including them one by one (and forgetting some in the process). 

I would be happy to see a feature like this in Asciidoc(tor) as well. I searched for it but didn't find an existing open ticket for this.

**Comment by mojavelinux** [comment] 2017-09-12 20:37
We can certainly consider this for core. But it's use cases like this that the include processor extension was designed to handle. In the include processor extension takes on the responsibility of interpreting and processing the target. So you can write the target using a glob pattern and the extension can find those files and include them.

**Comment by mojavelinux** [comment] 2017-09-20 05:21
I'd be happy to add this extension to the extension lab for demonstration purposes.

**Comment by mojavelinux** [comment] 2017-09-21 05:49
I have added this extension to the extensions lab. Please see:

https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/glob-include-processor/extension.rb

If that goes over well, we can consider adding it to core in the future.

**Comment by ahus1** [comment] 2017-09-23 09:36
Looks interesting. I'm just a bit confused with the options "separate" in the sample, and "discrete-option" in the code. Are they out of sync? What name do you prefer?

If I understand it correctly it's about adding a blank line between files. I've been there and search for the kind of problems you get once you have includes without blank lines...

I wonder: Should it be default?

**Comment by mojavelinux** [comment] 2017-09-26 05:34
Yes, that was a typo. And yes, I agree the inverse should be the default in this case.

Adjacent include directives should always be separated by blank lines unless the intention is to adjoin the content, such as in a listing block. However, since there's no way to pass those blank line when using a glob pattern, we should require an explicit option to keep the content adjoined.

**Comment by Weltraumschaf** [comment] 2018-07-09 15:58
Is this a duplicate to  #https://github.com/asciidoctor/asciidoctor/issues/855?

**Comment by obfischer** [comment] 2023-03-25 15:37
Ping for this IMHO important mechanism.

**Comment by mojavelinux** [comment] 2023-03-25 21:41
If you need this behavior, you should look to an extension. This is not something we're going to add in core, at least not anytime in the near future. For a starting point, see https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/main/lib/glob-include-processor/extension.rb

**Comment by mojavelinux** [comment] 2023-03-25 21:42
Closing as a duplicate of #855 anyway.

**Closed by mojavelinux** 2023-03-25 21:42 UTC
