### ISSUE TITLE
Fix parsing of lists at end of included documents

### ISSUE THREAD

**Issue by opoudjis** [asciidoctor/asciidoctor#3878] opened 2020-12-07 10:34 UTC
As of 2.0.11, lists at the end of included documents are not being processed correctly.

If a document includes two consecutive files, of which the first ends in an unordered list, and the second starts with a section heading, the section heading is included in the list, and is not processed as a section heading. This distorts the parsing of the document.

This behaviour does not occur in 2.0.10, and it does not occur if the included document is followed by inline content.

The attached file replicates the issue:

[test.zip](https://github.com/asciidoctor/asciidoctor/files/5652056/test.zip)

a.adoc
````
= X
A 

include::a1.adoc[]
include::a2.adoc[]
````

a1.adoc
````
== Clause

Clause para

* A
* B
````

a2.adoc
````
== Clause

* C

D 
````

Resulting a.html:

````
<div class="ulist">
<ul>
<li>
<p>A</p>
</li>
<li>
<p>B
== Clause</p>
</li>
<li>
<p>C</p>
</li>
</ul>
</div>
````

Note that the document

````
= X
A 

include::a1.adoc[]
== Clause

* C

D 
````

processes correctly.

Ruby version 2.6.6, OSX, but this issue is also impacting our docker-based builds.

**Comment by mojavelinux** [comment] 2020-12-07 11:02
This is a duplicate of #3875. In your case, it is happening because your include directives are not offset by a blank line. However, I realize many people have been relying on using blank lines at the top and bottom of their include files to separate blocks instead. So we need to rethink when the compression happens. Let's continue the discussion in that issue to keep it centralized.

**Comment by mojavelinux** [comment] 2020-12-07 11:03
As a general rule though, you should be putting blank lines between includes when it you are including AsciiDoc content. Putting blank lines inside the include documents is brittle.

**Closed by mojavelinux** 2020-12-07 11:02 UTC
