### ISSUE TITLE
Errors when using pygments

### ISSUE THREAD

**Issue by msc-** [asciidoctor/asciidoctor#1439] opened 2015-07-24 13:57 UTC
When I try to use the pygments source highlighter I get the following large number of warnings and the source is not highlighted. Am I doing something wrong?

```
/Library/Ruby/Gems/2.0.0/gems/posix-spawn-0.3.11/lib/posix/spawn/child.rb:161: warning: assigned but unused variable - boom
/Library/Ruby/Gems/2.0.0/gems/posix-spawn-0.3.11/lib/posix/spawn/child.rb:200: warning: assigned but unused variable - offset
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55: warning: loading in progress, circular require considered harmful - /Library/Ruby/Gems/2.0.0/gems/posix-spawn-0.3.11/lib/posix/spawn.rb
	from /usr/bin/asciidoctor:23:in `<main>'
	from /usr/bin/asciidoctor:23:in `load'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/bin/asciidoctor:10:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:86:in `invoke!'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:86:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:94:in `block in invoke!'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1499:in `convert'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/document.rb:1028:in `convert'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/converter/base.rb:34:in `convert'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/converter/html5.rb:96:in `document'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/stylesheets.rb:79:in `embed_pygments_stylesheet'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/stylesheets.rb:74:in `pygments_stylesheet_data'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/stylesheets.rb:88:in `load_pygments'
	from /Library/Ruby/Gems/2.0.0/gems/asciidoctor-1.5.2/lib/asciidoctor/helpers.rb:20:in `require_library'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/pygments.rb-0.6.3/lib/pygments.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/posix-spawn-0.3.11/lib/posix/spawn.rb:6:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/posix-spawn-0.3.11/lib/posix/spawn/child.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/2.0.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:100: warning: instance variable @pid not initialized
/Library/Ruby/Gems/2.0.0/gems/pygments.rb-0.6.3/lib/pygments/lexer.rb:39: warning: shadowing outer local variable - extname
```

**Comment by mojavelinux** [comment] 2015-07-24 16:57
I've never seen that problem before. I wonder if it is a general issue with
dependencies or something caused by the source code you are highlighting.

Could you provide a sample AsciiDoc document that triggers this exception.
That way, we're starting debugging on the same page.

**Comment by msc-** [comment] 2015-07-24 23:31
The warnings only appear with`asciidoctor -v` and now that I have got a `python2` in my path, the source code is highlighted despite the warnings. If you still need a sample document, let me know.

**Comment by mojavelinux** [comment] 2015-07-25 00:22
Aha, so you are probably seeing warnings Ruby is throwing from the pygments.rb gem. Warnings in Ruby are harmless ;)

**Comment by mojavelinux** [comment] 2015-07-25 00:23
Can we close the issue? If you feel like there is a documentation task that is needed, don't hesitate to say it. Perhaps we need to be more specific about the requirements for using Pygments.

**Comment by msc-** [comment] 2015-07-25 00:27
Yes, we can close this issue. When I first tried to use Pygments, Asciidoctor told me what gem to install which is sufficient.

**Closed** 2015-07-25 00:27 UTC

**Comment by mojavelinux** [comment] 2015-08-03 06:31
I updated the user manual to make it clear that Python 2, not Python 3, is required to use the pygments.rb gem.
