### ISSUE TITLE
{doctitle} attribute is ignored in table when cell is using AsciiDoc styles

### ISSUE THREAD

**Issue by CosmicMac** [asciidoctor/asciidoctor#2555] opened 2018-02-06 16:02 UTC
Hello,

The `{doctitle}` attribute is left unparsed in a table when the cell is using AsciiDoc styles.
No problem with standard cells.
No problem with other attributes.

Here is a simple example:
```
= My title
Cosmic Mac
v1.0, 2018-02-06

|===
| My title is: {doctitle}
a| My title is: {doctitle}
a| V{revnumber}, {revdate} - {author}
|===
````

Cheers!

**Comment by mojavelinux** [comment] 2018-02-18 07:11
This is by design. An AsciiDoc table cell is a separate AsciiDoc document and therefore has it's own doctitle (which is blank if it doesn't have one).

If you want to be able to use the doctitle from the parent in the AsciiDoc table cell, you need to alias it to other attribute so it doesn't get shadowed.

```
= My title
Cosmic Mac
v1.0, 2018-02-06
:parent-doctitle: {doctitle}

|===
| My title is: {doctitle}
a| My title is: {parent-doctitle}
|===
```

The same would go for all header attributes that are set implicitly (doctitle, author, revdate, revnumber, etc).

**Comment by CosmicMac** [comment] 2018-02-18 11:24
Actually only doctitle is shadowed in my example.
Author, revdate and revnumber are fine.
Anyway, the alias trick is OK for me.
Thanks for your time!

**Comment by mojavelinux** [comment] 2018-02-18 11:31
Ah, thanks for pointing that out. As it turns out, author, revdate and revnumber only shadow if they are defined in the nested document. The doctitle attribute is always reassigned.

**Closed** 2018-02-22 06:43 UTC
