### ISSUE TITLE
Problem when using leveloffset with preprocessor extension and include child adoc file

### ISSUE THREAD

**Issue by klod35** [asciidoctor/asciidoctor#3978] opened 2021-03-24 13:37 UTC
Hi,
i'm facing some title problems with those attached files.

I define a root leveloffset in the parent.adoc file and use the parameter leveloffset when I include the child.adoc file.
The generation of my pdf is ok, the whole title have the right level.

The problem came when I use a preprocessor extension. The leveloffset seems to be reseted after the page including and some titles have wrong right level.

Maybe I make something wrong but I don't understand why it works without the extension but not with it.

Can you explain me if I make a mistake ? All files are in the attached file.

[asccidoctor.zip](https://github.com/asciidoctor/asciidoctor/files/6197585/asccidoctor.zip)

**Comment by mojavelinux** [comment] 2021-03-24 22:29
The preprocessor extension has side effects (such as this one) and should be avoided if possible. We learned of these side effects after it was introduced. Since people do rely on this extension, we can't remove it. But we can recommend using alternatives.

Preprocessing during normal conversion is very complex because it's coupled with the parser. The preprocessor allows you to run the preprocessing step without the parser involved, which is what introduces these side effects. It's something you can work around with enough code, but it requires a lot of effort and it's not something I have time to help you with.

Suffice to say, this is a known issue / limitation of using a preprocessor.

**Comment by klod35** [comment] 2021-03-25 08:27
Ok. Thank you for the quick response.

**Comment by mojavelinux** [comment] 2021-03-25 09:43
> Suffice to say, this is a known issue / limitation of using a preprocessor.

I'd like to add that this is something we will be working on addressing in the AsciiDoc language project (the project that will produce the AsciiDoc specification).

**Comment by UnasZole** [comment] 2023-09-19 17:24
Hi,

I just stumbled on the exact same problem, after spending a few days days developping a preprocessor extension.

**First, I'd advise adding a big bold red warning to your documentation page about preprocessor extensions**, if you consider they have unfixable issues.
As it stands, your documentation page makes it look perfectly fine to use : https://docs.asciidoctor.org/asciidoctorj/latest/extensions/preprocessor/

(And if they shouldn't be used, **what other extension type gives the ability to read comments ?** Your AST documentation seems to imply that the comments are not at all included in the AST : https://docs.asciidoctor.org/asciidoctorj/latest/extensions/ast-introduction/ )

**Second, here is my understanding of the actual issue.**

I just had a look at the generated asciidoc in output of the preprocessor, and includes with a leveloffset have been replaced by this : 

```
:leveloffset: +2

:leveloffset!:
```

The problem is the usage of the absolute ":leveloffset!:" to reinitialise the offset level.
Printing a relative offset instead at the end of an include would solve everything.

In fact, your documentation on level offsets explicitly says "Relative levels are preferred". ;-)
cf. https://docs.asciidoctor.org/asciidoc/latest/directives/include-with-leveloffset/

My understanding is that this takes place here in the reader : 
https://github.com/asciidoctor/asciidoctor/blob/354a22ffdd753f4760cbfca4db96a4b77937b1ad/lib/asciidoctor/reader.rb#L719

Essentially, whenever you encounter an include with a leveloffset, you first print a line to reset the level offset to the one set at document level before printing the new offset.

The simplest fix would be storing a "stack of offsets" in the reader's state. To set a new relative offset, we push it to the stack and print the leveloffset. To reset the offset, we just pop the stack's topmost offset, and print a relative leveloffset with its negated value.

I'm not familiar with Ruby at all, but if you think that strategy is acceptable, I'd be willing to give it a shot and try to open a PR !

Regards,

**Comment by UnasZole** [comment] 2023-09-19 18:44
For anyone else with the same issue, the following workaround is possible (here in Java, as I'm writing my preprocessor extension for asciidoctorj) : 


```java

public class MyPreProcessor extends Preprocessor {

    private static final String LEVELOFFSET_PREFIX = ":leveloffset:";
    private static final String LEVELOFFSET_RESET = ":leveloffset!:";

    /**
     * Fix level offset directives due to https://github.com/asciidoctor/asciidoctor/issues/3978
     * @param line The line read from the source.
     * @param levelOffsets The stack of level offsets encountered so far.
     * @return The line to consider (potentially corrected if it was a leveloffset directive).
     */
    private String fixLevelOffset(String line, Deque<String> levelOffsets) {
        String trimmed = line.trim();
        if(trimmed.startsWith(LEVELOFFSET_PREFIX)) {
            // New level offset : put it on the stack, but nothing to change on the line.
            levelOffsets.push(line.substring(LEVELOFFSET_PREFIX.length()).trim());
        }
        else if(trimmed.startsWith(LEVELOFFSET_RESET)) {
            // Level offset reset : if we had level offsets in the stack, replace by a specific revert
            // of the top most.
            if(!levelOffsets.isEmpty()) {
                String topOffset = levelOffsets.pop();

                if(topOffset.startsWith("+") || topOffset.startsWith("-")) {
                    // Relative offset : revert by an opposite relative offset.
                    return LEVELOFFSET_PREFIX + " " + (0 - Integer.valueOf(topOffset));
                }
                else {
                    // Absolute offset : determine the absolute offset to revert to by accumulating all previous
                    // relative offsets.
                    Iterator<String> offsetIter = levelOffsets.iterator();
                    int relativeOffset = 0;
                    int previousAbsoluteOffset = 0;
                    while(offsetIter.hasNext() && previousAbsoluteOffset == 0) {
                        String offset = offsetIter.next();
                        if(offset.startsWith("+") || offset.startsWith("-")) {
                            // It's a relative offset : add it.
                            relativeOffset += Integer.valueOf(offset);
                        }
                        else {
                            // It's an absolute offset : time to stop the loop.
                            previousAbsoluteOffset = Integer.valueOf(offset);
                        }
                    }
                    return LEVELOFFSET_PREFIX + " " + (previousAbsoluteOffset + relativeOffset);
                }
            }
        }

        return line;
    }

    @Override
    public void process(Document document, PreprocessorReader preprocessorReader) {
        List<String> lines = preprocessorReader.readLines();
        List<String> outputLines = new ArrayList<>();
        Deque<String> levelOffsets = new ArrayDeque<>();

        Iterator<String> lineIterator = lines.iterator();
        while (lineIterator.hasNext()) {
            String line = fixLevelOffset(lineIterator.next(), levelOffsets);
            // Do whatever logic your extension needs with this line.
            outputLines.add(line);
        }

        preprocessorReader.restoreLines(outputLines);
    }
}

```

**Comment by mojavelinux** [comment] 2023-10-03 09:04
> I'd advise adding a big bold red warning to your documentation page about preprocessor extensions

I'd welcome such a contribution. We discovered sometime after introducing extensions that the preprocessor extension has gross side effects and therefore should not be used to read lines from the reader unless you are willing to address those side effects. You can draw from the statement I've made here: https://asciidoctor.zulipchat.com/#narrow/stream/279642-users/topic/.E2.9C.94.20Preprocessor.20extension.20documentation.3F/near/341640589

We are working on addressing the flaws in the preprocessor and preprocessor extensions in the spec.

> The simplest fix would be storing a "stack of offsets" in the reader's state. 

I assure you it is not simple. If it were, I would have changed it years ago. But the preprocessor has no knowledge of the document parsing and therefore cannot store information that the parser can access. That's why we have to use the hack of inserting `leveloffset` attribute entries around the included content, but that has some inherent limitations.

The real solution here is to avoid the preprocessor extension and instead do the work in either an include processor extension or a tree processor. We are not going to change how this works in Asciidoctor until we have completed the first version of the specification since we want to solve this the right way.

**Comment by mojavelinux** [comment] 2023-10-03 09:06
> The problem is the usage of the absolute ":leveloffset!:" to reinitialise the offset level. Printing a relative offset instead at the end of an include would solve everything.

If you can figure out how to switch to a relative offset instead of unsetting the leveloffset, I'd be interested to see that PR. Maybe we can find an interim solution.

**Comment by UnasZole** [comment] 2023-10-03 12:28
Thanks for your answer :-) 

Indeed, after writing the comment, I looked in more details at the architecture, and while the problem is easy to spot, it's hard to solve given the current architecture.
Which is why I spent time designing a clean workaround on the plugin side. Even though it would definitely be worth finding a proper fix (I might look into it again in the near future), that workaround can be enough for the time being.

In fact, maybe it would be a good idea to integrate my code as a helper class inside the asciidoctorj project, to make it at least easily accessible by anyone developing a preprocessor plugin - if you think it's a good idea I could open a PR there :-)

Regarding the edition of the documentation to highlight the issue when working with preprocessor plugins, should I open PRs editing the following files ?
https://github.com/asciidoctor/asciidoctor/blob/main/docs/modules/extensions/pages/preprocessor.adoc
https://github.com/asciidoctor/asciidoctorj/blob/main/docs/modules/extensions/pages/preprocessor.adoc

**Comment by mojavelinux** [comment] 2023-10-03 20:26
> while the problem is easy to spot, it's hard to solve given the current architecture.

well said

> maybe it would be a good idea to integrate my code as a helper class inside the asciidoctorj project, to make it at least easily accessible by anyone developing a preprocessor plugin

That's going to be up to the AsciidoctorJ project/maintainers.

>  should I open PRs editing the following files ?

That looks like the right location to me.

**Comment by mojavelinux** [comment] 2024-02-13 10:18
Just to be clear, the way the preprocessor works is that it sets the leveloffset specified on the include directive using an attribute entry, then it adds the lines to the reader, then it restores the leveloffset to the absolute value it had before the include directive.

If you need more control over the behavior of the leveloffset attribute, your best bet is to not use the leveloffset attribute on the include directive and, instead, set the leveloffset around the include directive. That way, it behaves exactly as you need it to.

With that said, I have nothing else to add to this conversation and I'm going to close it. Feel free to bring this up again in the project chat or file a more actionable issue that we can address.

**Closed by mojavelinux** 2024-02-13 10:18 UTC
