### ISSUE TITLE
Add possibility to use figure number or text in link text

### ISSUE THREAD

**Issue by megathaum** [asciidoctor/asciidoctor#858] opened 2014-01-07 14:53 UTC
I would like to write
"The overall architecture of the system is shown in Figure 1."
instead of 
"The overall architecture of the system is shown in "System overview". 

In printed documents (PDF) it is much more convenient for the reader to look up the figure by number than by text. Moreover, as the caption describes the figure and that information is already provided in the text that refers to the figure it makes no sense to repeat it.

**Comment by jmini** [comment] 2015-02-04 07:19
From a LaTeX point of view, what asciidoctor supports now is `\refname{system_overview}` and the missing feature is `\ref{system_overview}`.

[Related discussion](http://discuss.asciidoctor.org/How-to-reference-a-figure-with-its-number-td1260.html).

**Comment by jxxcarlson** [comment] 2015-02-04 07:43
Could you clarify what you mean?  Thanks!

**Comment by jxxcarlson** [comment] 2015-02-04 07:51
I think I understand now — I hadn’t looked at the discussion.

**Comment by jmini** [comment] 2015-02-04 08:01
In the project I am working for, we would like to have a single way of writing documentation. For the moment we have plain HTML pages, MediaWiki pages and documents produced with LaTeX. This is a great oportunity for me to check missing (or nice-to-have) features in Asciidoctor.

In our current LaTeX document, we use most of the time `\ref` and sometimes `\refname`.

To obtain:
> The overall architecture of the system is shown in Figure 1.

The LaTeX code is:

    The overall architecture of the system is shown in Figure~\ref{system_overview}

This issue is exactly about adding this missing feature. With Acsiidoctor:

    The overall architecture of the system is show in <<system_overview>>.

Produces: 
> "The overall architecture of the system is shown in System overview

I miss something like `<<system_overview,Figure ?>>` where the `?` should be replaced at generation time by the correct figure number in this document. (This is only a syntax proposition. As you understood it, I am not an Asciidoctor expert).

**Comment by jxxcarlson** [comment] 2015-02-04 08:38
Very good points — I later understood what you meant from the discussion, and I agree with it.
I need it myself!

A couple of things that you might be interested in related to Asciidoctor and LaTeX.

(1) We are working on Asciidoctor-latex, an extension which (a) adds latex-lke
functonality to Asciidoctor, and (b) which will allow one to convert an Asciidoctor
document to latex.  Part (a) is already being used at http://noteshare.io <http://noteshare.io/> — more on
this below.  Part (b) has  working prototype, but this needs more work.  I am also
working on a latex to asciidoctor converter, but this is much less advanced.

(2) Noteshare.io is a plafform for composing and distributing content on the web,
e.g., lecture notes.  Below are some examples, some with mathematical content.

	http://epsilon.my.noteshare.io/section/elliptic-curves <http://epsilon.my.noteshare.io/section/elliptic-curves>

	 http://noteshare.io/section/a-sample-document <http://noteshare.io/section/a-sample-document>

	http://www.noteshare.io/tour <http://www.noteshare.io/tour>
	
If you would like to create an account for yourself to see how content
creation works, the access code is C7092 at http://www.noteshare.io/ <http://www.noteshare.io/>

What sort of documentation are you working on?

**Comment by jmini** [comment] 2015-04-29 17:54
For the HTML output I am now using some java code (using JSoup) applied after the Asciidoctor toolchain. ([discussion](http://discuss.asciidoctor.org/How-to-reference-a-figure-with-its-number-tp1260p3059.html) and [java code](https://gist.github.com/jmini/230e5d4be48c1a0533eb))

**Comment by mojavelinux** [comment] 2015-05-02 21:59
This issue is related to #1132.

**Comment by mojavelinux** [comment] 2015-05-02 22:26
> I miss something like <<system_overview,Figure ?>> where the ? should be replaced at generation time by the correct figure number in this document. 

I'm intrigued by this idea. We could use a dynamic attribute assignment so that we can stay more inline with the AsciiDoc syntax:

```
<<system_overview,Figure {refnum}>>
```

**Comment by jmini** [comment] 2015-05-03 10:34
<<system_overview,Figure {refnum}>>

+1 to this idea.

Of course it should also work in the [reftext definition](https://github.com/asciidoctor/asciidoctor.org/issues/380):

    [[SystemOverview,Figure {refnum}]]
    .System overview
    image::SystemOverview.png[]

**Comment by otavio** [comment] 2015-05-05 22:21
I dislike Figure being hardcoded. This makes hard translating docs for example.

**Comment by mojavelinux** [comment] 2015-05-05 22:29
> I dislike Figure being hardcoded. 

By all means, that was just an oversight in the example. While I'm still leaning towards a global template, you'd have the option to do:

```
<<system_overview,{figure-caption} {refnum}>>
```

**Comment by otavio** [comment] 2015-05-06 13:08
This is nicer. However couldn't this to be automated with the template and every figure cite to be done this way?

**Comment by jmini** [comment] 2015-05-06 16:55
This is exactly the same topic for Listings:

````Asciidoc
:listing-caption: Listing

Check the <<lst-helloworld>> that prints "Hello World!" on the console.

[[lst-helloworld, Listing Hello World]]
.An "Hello World!" in Java
----
System.out.println("Hello World!");
----
````

It would be nice to be able to write:

````Asciidoc
Check the <<lst-helloworld,{figure-listing} {refnum}>> that prints "Hello World!" on the console.
````

And/or:

````Asciidoc
[[lst-helloworld, {listing-caption} {refnum}]]
.An "Hello World!" in Java
----
System.out.println("Hello World!");
----
````

And/or as proposed by @otavio with a single configuration for all listings.

**Comment by indigo423** [comment] 2015-05-27 13:23
:+1: for this improvement.

**Comment by wolandscat** [comment] 2015-06-20 10:54
Just to add, we have probably 1,500 pages of technical standards documentation, being converted from FrameMaker, which has a lot of power to easily do things like references to 'Figure 4' (and note that the 'Figure' comes from a style definition for figure para type in the style catalog).

It may be useful to understand how FrameMaker does this, to think about how it could be done here. in Frame, you can create named cross-reference definitions, made up of separate builtin variables like <$paranum>, <$pagenum>, <$paraname>, interspersed with static text. So I can have Xref definitions like:

    Figure: <$paranum> on <$pagenum>
    FigureShort: <$paranum>
    etc

Note that I don't have to put any literal 'Figure' here, because it is part of the Figure paragraph definition, which has a leader defined as:

    "Figure <n+>:\t"

As you can see, there are multiple levels of definition and processing implied here, but I think it is unavoidable, if this is to be gotten right in newer tools that want to implement non-basic behaviour (which I hasten to note, is considered utterly basic by people coming from DTP, publishing and technical documentation environments ;-)

**Comment by jxxcarlson** [comment] 2015-06-20 12:16
Amen!  I vote for this and with a syntax that is as lean as possible.

**Comment by jxxcarlson** [comment] 2015-06-20 12:28
Addendum — can we do something like the following (I believe this
is what Otavo is suggesting)

(1) have a style file where the user can define choices

(2) Suppose we have the figure

.Event horizon
image::suck.jpg[width=300, align=center, id=event_horizion]

and that later we say

And for the proof that my ideas regrading
black holes are correct,  I refer you gentlemen 
to <<event_horizon>>.

(3) Then the figure is displayed with “Figure 23. Event Horizon” 
centered under the figure (since the style file defines it this way)

(4) And the reference is rendered as “I refer you gentlemen to Figure 23”

The point is to (a) have the most streamlined and elegant syntax as 
possible along with (b) flexibility via the style file to alter the defaults,
(c) thereby making everyone happy.

**Comment by shahryareiv** [comment] 2015-06-29 11:24
Another example is from Latex world, \cref{} macro (Clever Ref) does the same thing \cref{some-lablel} becomes Fig X, Section Y, Table Z, ... depending on the location of the original \label{some-lable}. It also supports capital form through \Cref{}. Wordings ("Fig", "Section", ..) and delimiters (Fig. or Fig: or Fig-, ...) are customizable.

**Comment by nathany** [comment] 2015-08-21 06:32
I'm currently specifying the title of figures, tables, and listings when defining an xref anchor.

```adoc
[[table-integer-types,Table 2.1]]
...

as summarized in <<table-integer-types>>.
```

```adoc
[[tickets.go,Listing 1.9]]
.Tickets: tickets.go
[source,go]
----
include::{sourcedir}/tickets.go[]
----

When you run <<tickets.go>>
```

This is better than specifying it as part of every reference back to the figure/table/listing, but it would be nice to automate the numbering, particularly when a chapter is reorganized.

**Comment by nathany** [comment] 2015-08-22 02:06
After a little more thought, here is a new suggestion for auto-numbering:
https://github.com/asciidoctor/asciidoctor/issues/1434#issuecomment-133625546

**Comment by jmini** [comment] 2015-11-21 18:09
> I'm currently specifying the title of figures, tables, and listings when defining an xref anchor.

The possibility to use `{refnum}` in the anchor definition for table was asked on the mailing list:
http://discuss.asciidoctor.org/Referring-to-a-numbered-table-td3967.html#a3971

**Comment by filiphr** [comment] 2016-01-12 07:57
I couldn't quite understand. Is the functionality ```[[SystemOverview,{figure-caption} {refnum}]]``` implemented, or not? If yes then it is not working for me with the latest released version. The ```{figure-caption}``` in the ```reftext``` is not replaced. Whereas in ```<<SystemOverview, {figure-caption} {refnum}>>```. The ```{figure-caption}``` is replaced. The ```{refnum}``` is not replaced in both cases.

**Comment by k-mack** [comment] 2016-02-10 13:50
As a side note, what I tend to do is to capture this in attributes. Since section identifiers rarely change and I generally desire to have strong consistency for the cross reference texts used within a document, I create a listing of attributes to summarize how they look:

```
= Level 0

// Figures
:fig1: <<img-turtle, Figure 2>>

// Sections
:sect1: <<introduction, Section 1>>

[#introduction]
== Level 1

Look at the green turtle in {fig1}. Enjoying {sect1} yet?
```

I like this because you only need to change the cross reference text in a single location.

**Comment by shahryareiv** [comment] 2016-02-11 10:19
@k-mack 
The problem with your solution is if that one needs to always keep track of the orders of figures or sections so for example Figure 13 is really the 13th and not the 12th. In real life an author might need to move these things around a lot.

**Comment by jmini** [comment] 2016-02-12 04:16
@shahryareiv: +1 to your comment.

We reuse some code blocs (containing figures) in different documents. The number assigned to the figure is not the same depending of this context.
We definitively need something dynamic, as described in this bug.
I have a HTML post-processing workaround but for PDF something like that does not work.

**Comment by shahryareiv** [comment] 2016-02-12 12:26
@jmini 
Actually I have used the method suggested by Dan in https://github.com/asciidoctor/asciidoctor/issues/1381#issuecomment-165407405 and it works almost well. There some glitches and need for enhancements that were discussed in this issue and some others.

**Comment by sanmai-NL** [comment] 2016-04-19 13:22
@mojavelinux: Today, I wished to create a cross-reference to a section that includes the section number. Motivation: I think this is important to aid the reader, and crucial for print documents (as already suggested by @megathaum). To be sure I tested the `{refnum}` suggestion that came up in this thread, but that does not work right now with version 1.5.4. Suppose I want to contribute toward this feature, where in the codebase should I focus my attention?

**Comment by getreu** [comment] 2016-09-15 14:56
+1 for [issuecomment-63163932](https://github.com/asciidoctor/asciidoctor/issues/858#issuecomment-63163932):
>    it would be nice to have the same 3 styles available: xref, xref-number and xref-number-and-title

By default docbook renders references like this
* _Section  7.6, “Functionality oriented validation”_
or just
* _Section 7.6_ 

I need both versions in HTML5. Now with the new [labels](http://asciidoctor.org/docs/user-manual/#customizing-labels) the groundwork is in place. Are there any news? 


*) The numbered only version you get with `<xsl:param name="xref.with.number.and.title" select="0"></xsl:param>`

**Comment by mojavelinux** [comment] 2017-05-16 06:55
For those wondering if this is implemented...if the issue is still open that means it's not implemented. Issues close automatically when the corresponding code is merged. Right now, we just have proposals.

**Comment by mojavelinux** [comment] 2017-05-16 06:55
It seems pretty clear to me that this is a global setting. If you have references styled in a certain way, it probably is consistent throughout the document.

Therefore, I still think the right solution is to have some built-in modes and support for a custom pattern that uses AsciiDoc-like attribute references. So something like:

```
:xref-style: reftext
```

or

```
:xref-style: number-reftext
```

or

```
:xref-style: number
```

or

```
:xref-style: \{label} \{number}. \{reftext}
```

(the backslashes are required to prevent substitution when the attribute is defined; you could also use pass:[])

The only think that doesn't account for is that different objects (figures, listings, sections) may need different formats. Therefore, we may need to break this down to `figure-xref-style`.

Of course, if you specify custom reftext on a particular item, then I think that would replace the "reftext" part (as what you are typically customizing is the text).

Here's how I define the parts:

```
       v number
Figure 1. System Overview
^ label   ^ reftext (defaults to title)
```

We can get fancier about this in the future, but this at least gets us started.

**Comment by mojavelinux** [comment] 2017-05-16 07:45
Instead of "label-number-reftext", "label-number", and "reftext", I propose "formal", "brief", and "informal" (or "casual"). Although less specific, they are more to the point and perhaps easier to remember.

**Comment by mojavelinux** [comment] 2017-05-16 07:48
I'm pretty sure this design is going to work. At the same time, we may be able to solve #1694 at the same time in a better way.

The key is to store the target node in the references table instead of the reftext (which defaults to the title). This allows the reference text to be resolved during conversion instead of during parsing, which gives us access to the whole structure of the document...and we can perform substitutions in the value as needed.

**Comment by shahryareiv** [comment] 2017-05-16 08:37
Capital beginning and formatting might be a part of the requirement. Some styles require "Figure" anywhere in the sentence and some consider it a normal word. At the same time it might be needed to boldify or colorize "Figure 1." in some styles.

**Comment by wolandscat** [comment] 2017-05-16 13:15
In FrameMaker I used to use something like 'FigureShort' (meaning "Fig. 5") and 'Figure', ("Fig. 5 on page 27"). Similarly for other kinds of xrefs (for which by the way, FrameMaker was the champion tool for 25 years - there were a lot of ways to define xrefs in FM, all configurable.)

I have to say 'formal', 'brief' and 'informal' are not very helpful to me - they are subjective words, so I probably don't know what 'informal' really means for example. 

It's definitely a global setting.

**Comment by mojavelinux** [comment] 2017-05-16 19:52
>  there were a lot of ways to define xrefs in FM, all configurable.

Keep in mind, most aspects of Asciidoctor or configurable via extensions (with enough creativity applied). What we're talking about here is having a simple switch that you can rely on in most environments (like on GitHub for instance). The new design will also make it a lot easier to apply an extension because we'll be saving the node, and using a helper method, instead of just pulling the text from a pre-made table.

> In FrameMaker I used to use something like 'FigureShort' 

Then perhaps we should consider names like "full", "short", and "default" instead (kind of taking a page from git log). These are just built-ins, so it's not like you can't override it.

**Comment by mojavelinux** [comment] 2017-05-16 19:55
>  formatting might be a part of the requirement.

That's already accounted for in the pattern value:

```
xref-style: *\{label} \{number}.* {reftext}
```

> Capital beginning 

This is much, much harder because it means knowing where we are in the sentence...and that is just not something the inline parser knows right now. I don't want to cause this whole feature to get held up because of that, so I think that's a solve later kind of problem.

**Comment by wolandscat** [comment] 2017-05-16 22:51
Just to be clear, I am not suggesting that my old names like figureshort etc are good candidates. I'd rather you chose the names that feel right to you, it will be more consistent. I just have a thing against names that are subjective, because everyone interprets them differently.

**Comment by mojavelinux** [comment] 2017-05-16 23:29
That's very true. Though, the use of "porcelain" names have been well proven (in programs like git and bash), so I think it's reasonable to build on that convention as long as it feels like a good fit.

**Comment by mojavelinux** [comment] 2017-05-24 07:38
> The point is to (a) have the most streamlined and elegant syntax as possible along with (b) flexibility via the style file to alter the defaults, (c) thereby making everyone happy.

Amen. Working with that in mind.

**Comment by mojavelinux** [comment] 2017-05-24 08:01
One of the things that's been making this so tough to solve is that the underlying model was not complete. For example, we weren't storing the number for numbered blocks. We also didn't have an easy way to check whether a section is a chapter or a part. We also didn't have language strings for a chapter and a section. So I've been working recently to rectify that model.

The other part that makes this hard is the sheer number of permutations we have to deal with. To make sure we have them all covered and we're handling them correctly, I'm going to list them here.

## xrefstyle=full

* **part** — Part Title
* **numbered chapter** — Chapter 1, *Chapter Title*
* **numbered section** — Section 1.1, “Section Title”
* **appendix (book)** — Appendix A, *Appendix Title*
* **appendix (article)** — Appendix A, “Appendix Title”
* **unnumbered chapter** — *Chapter Title*
* **unnumbered section** — Section Title
* **figure with title** — Figure 1, “Figure Title”
* **example with title** — Example 1, “Example Title”
* **table with title** — Table 1, “Table Title”
* **listing with title (if listing-caption attribute is set)** — Listing 1, “Listing Title”
* **other block with title** — Block Title

As of now, Asciidoctor always numbers appendices and never numbers parts.

## xrefstyle=short

* **part** — Part Title
* **numbered chapter** — Chapter 1
* **numbered section** — Section 1.1
* **appendix (book)** — Appendix A
* **appendix (article)** — Appendix A
* **unnumbered chapter** — Chapter Title
* **unnumbered section** — Section Title
* **figure with title** — Figure 1
* **example with title** — Example 1
* **table with title** — Table 1
* **listing with title (if listing-caption attribute is set)** — Listing 1
* **other block with title** — Block Title

## xrefstyle unset (default)

If the xrefstyle attribute is not set, the behavior matches the existing behavior.

## Overrides and exceptions

If explicit reftext is specified either at the xref location or on the reference, that value is used as the xref label in all cases.

Cases not mentioned continue to behave in the same way as before.

**Comment by mojavelinux** [comment] 2017-05-24 08:04
I'll be introducing the following language attributes:

```
:chapter-label: Chapter
:section-label: Section
```

I'm deferring on introducing `part-label` in core until Asciidoctor supports numbering for parts. But we could start adding it to the translation file today.

It's interesting to note how Asciidoctor determines whether a formal block (a block with a title) should be assigned a title. It's based on whether the attribute `<blockname>-caption` is defined. That's why when you define `listing-caption`, the formal listings get numbered. You could do the same for literal blocks by defining `literal-caption`. We may need better control over this in the future, but that's the logic today.

**Comment by mojavelinux** [comment] 2017-05-24 08:38
I'm experimenting with a custom xref style. To prevent it from blocking the completion of this issue, I've filed that idea as a separate issue.

#2212

Don't worry, there's room for it in the current design. If the value of the `xrefstyle` attribute is not one of the built-in values, then we assume it's a formatting string.

**Comment by mojavelinux** [comment] 2017-05-24 08:55
I should have a PR ready in the next day or two to test.

**Comment by mojavelinux** [comment] 2017-05-25 06:58
The other issue to resolve here is which substitutions to apply to reftext and when. It stands to reason that we should apply the title substitutions since reftext is akin to the block title. That's the idea I was pursuing in #1694.

If we defer substitution until the converter, then the attributes resolved will be the ones visible at the location of the cross reference. This seems counter-intuitive to me since that's not where the reftext is defined and it differs from how the title works (which is the fallback value). However, if we substitute the reftext during parsing, then we are essentially doing conversion in the parse phase, which we already want to get away from doing. On the other hand, the benefit is that you can reference an attribute such as the block's counter:

```
[reftext="{figure-caption} {figure-number}, &#8220;Projections!&#8221;"]
```

(I don't really consider this to be a normal use case once this issue is resolved, but it shows what might be possible for special cases).

One middle of the road solution is to apply header subs (special characters and attributes) to the reftext (or just substitute attributes) when it gets parsed and assigned to the block*. Then in the converter we'd apply the remaining subs, which include text formatting. (We may even decide to do the same for the title in the future). While this would be a departure from how AsciiDoc has worked in the past, it seems most logical.

\* We could even do this only when interpolation is enabled, which is when the value is enclosed in single quotes. That really seems like the right choice here.

**Comment by mojavelinux** [comment] 2017-06-26 05:30
This issue is will be resolved when PR #2220 is merged.

**Comment by mojavelinux** [comment] 2017-06-26 05:35
> However, it would be nice to have the same 3 styles available: xref, xref-number and xref-number-and-title.

To be clear, these three styles are now implemented. The equivalent values for the `xrefstyle` attribute are are "full" (label + number + quoted title), "short" (label + number), and unset (title). Technically, we support a forth, which is the explicit reftext set on the referenced node. That value always takes precedence, regardless of the `xrefstyle` setting (also true in DocBook).

In the future, I might consider adding a `reftitle` attribute, which would substitute the title in the generated cross reference text, but not replace it entirely like the `reftext` attribute does.

**Comment by mojavelinux** [comment] 2017-07-01 23:58
After doing a bit more research, I'm going to always italicize the appendix title, even when the doctype is article.

Also, if the xrefstyle is set to basic, or xrefstyle is set but section numbering is off, chapter and appendix titles will be italicized.

**Comment by mojavelinux** [comment] 2017-07-02 00:34
Open question: If the label is undefined (for example, `:!section-caption:`), and the `xrefstyle` is full, which should be printed?

a.
```
1.5.1, “Section Title”
```

b.
```
Section Title
```

If the `xrefstyle` is short, which should be printed?

a.
```
1.5.1
```

b.
```
Section Title
```

**Comment by wolandscat** [comment] 2017-07-02 11:19
In FrameMaker, the 'full' style defaulted to something like:

```
section 1.5.1 on page 34
```

The page number is only useful in PDFs (where is really is useful, even in the electronic version, if there is no proper PDF TOC tree). 'Section 1.5.1' presupposes that your document parts are all 'sections', but maybe you want to point to just 'chapter 3'. OTOH, if you don't put a word before the '1.5.1'. it looks a bit strange to end up with text like

```
... which is described in 1.5.1, "Advanced Options" ....
```

but maybe that's just me. I think the default doesn't matter too much. If the default doesn't do what the user wants, they'll set a style explicitly. 

Nevetheless, I'd probably go for styles that include the number for both default cases, since cognitively, if the user doesn't click through, they will use that number to quickly visually scan the TOC tree.

**Comment by mojavelinux** [comment] 2017-07-03 00:18
I think you answered my question. We should refer to the section number even when the label (aka section-caption) is unset. Otherwise, we would be dropping information that was requested.

> 'Section 1.5.1' presupposes that your document parts are all 'sections'

I should have clarified that we use the label that corresponds to the type of target. In my example, I used "Section", but it would be the same for Chapter or Appendix (and in the future, Part).

> OTOH, if you don't put a word before the '1.5.1'. it looks a bit strange...

Actually, I've seen this done often in books and documentation I've read, which is why I think we need to provide a way to do it. But you'd definitely be intentionally configuring it to do that...so you know what you're doing. It's also possible to control it per target type (section vs appendix vs chapter).

> If the default doesn't do what the user wants, they'll set a style explicitly.

The custom style has been deferred. (#2212) Nevertheless, the logic is now centralized so it's possible to override the xrefstyle method until that point.

**Comment by getreu** [comment] 2017-07-03 03:35
Is there a way to produce the same result than Docbook does?

**Comment by mojavelinux** [comment] 2017-07-03 04:27
Exactly the same result using xrefstyle full (according to my tests).

**Comment by mojavelinux** [comment] 2017-07-09 20:42
Here's the documentation for this new feature:

http://asciidoctor.org/docs/user-manual/#customizing-the-cross-reference-text

**Closed** 2017-07-10 01:12 UTC
Labels: design, enhancement

**Comment by vogella** [comment] 2017-07-10 08:06
Thanks a bunch, @mojavelinux.

**Comment by mojavelinux** [comment] 2017-07-10 08:29
Thank *you* for your support. This was not easy to solve, but it was what we needed to move forward. It really pushed Asciidoctor to a new level and paved the way for what's to come.

**Comment by charlottedeclercq** [comment] 2017-12-07 08:43
Hi,

I read the documentation http://asciidoctor.org/docs/user-manual/#customizing-the-cross-reference-text but still can not manage to have the link displayed as Chapter 1 or Section 1.1 instead of France or Paris (in my example).



    :xrefstyle: full
    = Hello
    == France
    === Paris
    xref:France[]
    <<France>>
    <<Paris>>

Unfortunately this is rendered as 

![image](https://user-images.githubusercontent.com/23074561/33706038-f12bcba2-db32-11e7-8117-5c768d83ffa4.png)

I know I am missing something but what ?

I tried on online asciidoc too (https://asciidoclive.com/).

Thank you for your help.

Charlotte

**Comment by mojavelinux** [comment] 2017-12-07 09:39
The custom xref styles are only used for section references if section numbering is enabled on the document.

```
= Hello
:xrefstyle: full
:sectnums:

== France
=== Paris

xref:France[]

<<France>>

<<Paris>>
```

**Comment by charlottedeclercq** [comment] 2017-12-07 09:47
Hi thanks, 

This is still not working (and also not on the https://asciidoclive.com/).
I am using brackets with the preview. I assume I don't have the right version.
I don't know if this is embedded in the actual version of brackets-asciidoc-preview ?

**Comment by mojavelinux** [comment] 2017-12-07 10:23
The version of Asciidoctor must be 1.5.6.

**Comment by charlottedeclercq** [comment] 2017-12-07 10:37
Thank you.
