### ISSUE TITLE
Clickable Title

### ISSUE THREAD

**Issue by caigner** [asciidoctor/asciidoctor#3058] opened 2019-02-08 15:52 UTC
I use Asciidoctor 1.5.8.
I wanted to create a link in the main title. So I declared some attributes:

```
= {myurl}[{mytitle}]
:mytitle: Manufacture of liquid glue
:myurl: https://patents.google.com/patent/US1394654A/en
```
This is the corresponding line in html5:

```
<h1>https://patents.google.com/patent/US1394654A/en[Manufacture of liquid glue]</h1>
```

I expected more like this:

```
<h1><a href="https://patents.google.com/patent/US1394654A/en">Manufacture of liquid glue</a></h1>
```

Is this a bug or did I miss something?

**Comment by Mogztter** [comment] 2019-02-08 16:34
Hello @caigner 

Since you are using attributes, I think you need to be explicit about the link using `link:`

```
= link:{myurl}[{mytitle}]
:mytitle: Manufacture of liquid glue
:myurl: https://patents.google.com/patent/US1394654A/en
```

Maybe there's a better way to write it... hope it helps :wink:

**Comment by caigner** [comment] 2019-02-08 17:28
@Mogztter, that's brilliant! Works like a charm!
Thanks!

**Comment by mojavelinux** [comment] 2019-02-10 06:03
This is a duplicate of #1173, which we're planning to address in the upcoming 2.0.0 release. Follow that issue for updates.

**Closed by mojavelinux** 2019-02-10 06:03 UTC
