### ISSUE TITLE
Stray ending bracket (`}`) at end of CSS line causing HTML validation failure

### ISSUE THREAD

**Issue by ronaldtse** [asciidoctor/asciidoctor#2531] opened 2018-01-09 06:53 UTC
This line gives out a stray `}` at the end, causing the HTML5 output of Asciidoctor to fail validation (see [W3C validator](https://validator.w3.org/)).

https://github.com/asciidoctor/asciidoctor/blob/cc212a80ff739cc8e0a30fab6c9f685b0599fd69/data/stylesheets/asciidoctor-default.css#L417

This failure will also cause deployment to GitHub Pages to fail, leading to the infamous "404 page not found" for a given page that validates otherwise.

cc: @ribose-jeffreylau

**Comment by mojavelinux** [comment] 2018-01-09 07:10
That's not a stray bracket. It's closing the print media block.

The problem is actually that the validator is not allowing the `@page` selector inside the `@media` selector. There seems to be some debate about this. If I move it outside of the `@media` selector, then the page validates and it still has the same behavior. Therefore, I'll proceed with moving it.

**Comment by ronaldtse** [comment] 2018-01-09 07:39
@mojavelinux you're absolutely right. Sloppiness on my part with this -- thank you for the fix.

**Comment by mojavelinux** [comment] 2018-01-09 08:29
:+1: 

I reopened to allow the PR to close the issue.

**Comment by mojavelinux** [comment] 2018-01-09 08:30
Actually, you weren't wrong to report it as you did. Technically it's the validator that is misleading people. I only got lucky that I figured out which line it was.

**Closed** 2018-01-10 06:45 UTC
Labels: bug
