### ISSUE TITLE
At least some global attributes are ignored inside table cells

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3914] opened 2021-01-16 11:02 UTC
The second example still takes a caption label. That is, the name of the second example is "Example 1. bar". A bug?

```
:example-caption!:

.foo
====
a
====

|===
a|
.bar
====
b
====
|===
```

**Comment by mojavelinux** [comment] 2021-01-16 12:02
This is a duplicate of #2586.

**Closed by mojavelinux** 2021-01-16 12:02 UTC
