### ISSUE TITLE
Figure number unexpected behavior

### ISSUE THREAD

**Issue by nRbshk** [asciidoctor/asciidoctor#4514] opened 2023-11-08 08:26 UTC
Unexpected behavior of figure-number while using image macro and its attribute [caption=my-caption].

<details>
  <summary>Example</summary>

```asciidoc
:imagesdir: ./
:chapter-number: 1
:figure-caption: Figure {chapter-number}.

.Image one
image::f3.jpeg[]

figure-number={figure-number}

.Image two
image::f3.jpeg[]

figure-number={figure-number}

.Image three
image::f3.jpeg[caption=Figure {chapter-number}. {figure-number}]

figure-number={figure-number}

.Image four
image::f3.jpeg[]

figure-number={figure-number}

```
</details>

<details>
<summary>Result</summary>

![Screenshot from 2023-11-08 11-09-15](https://github.com/asciidoctor/asciidoctor/assets/82058690/4ffc04bb-20d7-45f8-a4b8-f20af19ef32f)

</details>

<details>
<summary>Expected</summary>

![Screenshot from 2023-11-08 11-14-08](https://github.com/asciidoctor/asciidoctor/assets/82058690/ee445e0d-b431-4655-9842-c66dd624b8fa)

</details>

<details>
<summary>Expected-2</summary>

![Screenshot from 2023-11-08 11-15-44](https://github.com/asciidoctor/asciidoctor/assets/82058690/cb82456d-e058-4cf8-881e-a6113fd5af7e)

</details>

The difference between result and expected is the figure-number after using attribute caption - figure-number doesnt increment if i use caption in image macro.

So there some questions:
- the figure number increments after the image was processed?
- its only increments only if it uses automatic caption?
</br>
Im using latest version of asciidoc  

```
vscode ➜ /workspaces/ip-sample (4.03a) $ asciidoctor -v
Asciidoctor 2.0.20 [https://asciidoctor.org]
Runtime Environment (ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by mojavelinux** [comment] 2023-11-08 08:50
This is not a supported way of customizing figuring numbering. If you want the numbering to be relative to the chapter number, you will need to write an tree processor extension that rewrites the caption after the document block structure has been parsed. You can find such an extension in the lab at https://github.com/asciidoctor/asciidoctor-extensions-lab/pull/113/files

This is a duplicate of #2291.

**Closed by mojavelinux** 2023-11-08 08:50 UTC
