### ISSUE TITLE
Is attaching to an ancestor list broken?

### ISSUE THREAD

**Issue by edl7878** [asciidoctor/asciidoctor#3851] opened 2020-11-11 17:35 UTC
```
* A
** B
*** C
**** D
***** E

+
Attaching paragraph to ancestor D
```

There is just one blank line between list item E and Attaching paragraph.

According to documentation, the paragraph would be attached to D, since there is only one blank line.

But it is attached to A.

![image](https://user-images.githubusercontent.com/1988479/98844499-63614200-241a-11eb-9dcb-7c7e65749ed1.png)

**Comment by mojavelinux** [comment] 2020-11-11 21:26
This is a duplicate of #2293 (and other linked issues). In brief, using blank lines to attach to ancestors just isn't realiable and is extremely difficult to fix given how the parser is currently implemented. It's best to follow the recommendations in that thread.

**Closed by mojavelinux** 2020-11-11 21:26 UTC

**Comment by edl7878** [comment] 2020-11-11 21:29
Got it. Thanks.
