### ISSUE TITLE
How to add roles to th or td elements

### ISSUE THREAD

**Issue by diarmuidkieran** [asciidoctor/asciidoctor#4077] opened 2021-06-07 14:43 UTC
It is possible to add specific classes to a table in asciidoc, as follows:

**ASCIIDOC**

```
[.custom]
[cols="40a,80a",options="header"]
|===

|*First Name*
|*Family Name*

|John
|Smith

|==
```

**HTML (after Antora run)**

```html
<table class="tableblock frame-all grid-all stretch custom">
<!-- ... -->
<thead>
<tr>
<th class="tableblock halign-left valign-top"><strong>First Name</strong></th>
<th class="tableblock halign-left valign-top"><strong>Family Name</strong></th>
</tr>
</thead>
<tbody>
<tr>
<td class="tableblock halign-left valign-top"><div class="content"><div class="paragraph"><p>John</div></div></td>
<td class="tableblock halign-left valign-top"><div class="content"><div class="paragraph"><p>Smith</p></div></div></td>
</tr>
```

So, the "role" of "custom" has been applied to the `<table>` element. However, I also want to specify specific properties for the `<th>`, `<tr>` and `<td>` elements. How do I do this ?

I have attempted:

```
|[.custom]*First Name*
```

for a `<th>` element, and:

```
|[.custom]John
```

for a `<td>` element

but this only gives me the following when converted to html:

```html
<th class="tableblock halign-left valign-top"><strong class="custom">First Name</strong> 
</th>
```
```html
<td class="tableblock halign-left valign-top"><div class="content"><div class="paragraph"><p>[.custom]John</p></div></div></td>
```

How do I achieve the following?

```html
<th class="tableblock halign-left valign-top **custom**"><strong>First Name</strong></th>
```

and

```html
<tr class="tableblock halign-left valign-top **custom**"><div class="content"><div class="paragraph"><p>John</p></div></div></td>
```

**Comment by Mogztter** [comment] 2021-06-07 20:05
This is actually a duplicate of https://github.com/asciidoctor/asciidoctor/issues/1338.
Currently, it's not possible to apply a custom role on a cell (`<td>` or `<th`).

In the future, please ask usage questions first in the community chat at https://asciidoctor.zulipchat.com.

**Closed** 2021-06-07 20:44 UTC
Labels: duplicate
