### ISSUE TITLE
Tag filtering with !* behaviour change

### ISSUE THREAD

**Issue by essennell** [asciidoctor/asciidoctor#4086] opened 2021-06-18 18:47 UTC
Sometime between 2.0.12 and 2.0.15 - a *patch* update - the behavior of !* for filtering tags has changed. The docs at https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/#tag-filtering have changed to reflect new behaviour, but this is quite an intrusive change.

For example I use filtering like so:

    // ... source

    class ignore_me { }

    // tag::outer[]
    class thing
    {
        // tag::select_inner[]
        public void fun() { }
        // end::select_inner[]
    }
    // end::outer[]

    class ignore_me_2 { }

I could previously (2.0.12) include just the `thing` declaration like this:

    include::{sourcefile}[tags=outer;!*]

This would give me just this in the output:

    class thing
    {
    }

The new behavior includes every non-tagged lines in the included file.
Is the change intentional? If so, what's the rationale?

The new docs for !* conflict directly with the documented behavior of the separate ! and * filters, and other uses, e.g. !select_inner.

**Comment by mojavelinux** [comment] 2021-06-18 18:51
I'll need to double check, but I'm quite certain this is due to a regression in 2.0.15 reported here: #4048. If so, the reason is it was a mistake and will be fixed in the upcoming release.

**Comment by essennell** [comment] 2021-06-18 18:54
> 
> 
> I'll need to double check, but I'm quite certain this is due to a regression in 2.0.15 reported here: #4048. If so, the reason is it was a mistake and will be fixed in the upcoming release.

Thanks for that. Sorry, didn't show up in a search for existing issues :) It definitely looks related to #3932, tagged at 2.0.13. I've reverted to 2.0.12 for now.

**Comment by mojavelinux** [comment] 2021-06-18 21:26
It turns out this isn't the same issue, though closely related. The problem is that the syntax you were relying on is not documented. Here's the correct syntax that works in all versions:

```
include::{sourcefile}[tags=outer;!**]
```

What that says is to only include tags and, of the tags, only include the tag "outer".

The tag filtering is not hierarchical. It does not understand "include this parent tag but exclude these child tags". Rather, it looks at which tags it is including and takes those. Then there is the question of whether to take the content outside of tags, which `!**` dictates.

The `!*` directive has always indicated to tag everything except tags (per the docs, "only selects regions that are not tagged"). You happened to be relying on a bug that would change the meaning of that directive if other tags were specified. I'm going to give some thought as to whether to carry on supporting that officially.

**Comment by mojavelinux** [comment] 2021-06-18 23:45
I've discovered a few other issues, and I think I can fix them all without breaking any existing test cases. However, the docs do stills stand. They describe the tag filtering the way we have always understood it. I do think we can add additional cases, such as `outer;!*`, and I will update that page to reflect these additions. But I refute the claim that we made an intrusive change when we documented the feature.

**Comment by mojavelinux** [comment] 2021-06-19 08:09
In the future, before just assuming we broke something intentionally in a patch release, I would appreciate if you gave us the benefit of the doubt and assume first that we made a mistake.

**Comment by mojavelinux** [comment] 2021-06-19 09:32
The root cause is that we were missing a whole bunch of tests. The change I have proposed does not break any existing tests, but does restore and verify the aforementioned behavior.

**Comment by mojavelinux** [comment] 2021-06-19 09:32
FYI: I'm working on getting out the 2.0.16 release this week.

**Closed** 2021-06-20 05:56 UTC
Labels: bug
