### ISSUE TITLE
Some environment attributes do not display

### ISSUE THREAD

**Issue by vikram-redhat** [asciidoctor/asciidoctor#3315] opened 2019-05-27 13:15 UTC
Using AsciiBinder (https://github.com/redhataccess/ascii_binder), which loads AsciiDoctor using the API, I am trying to output the docname, docfile and outfile environment attributes in my asciidoc file, but the value of none of these get printed. They render as {docname}, {docfile} and {outfile} verbatim respectively. Some environment attribute values get printed. For example, there is no issue using {doctitle} or {docdir}.

My question is, are there any circumstances where certain environment attributes won't get parsed for the output using the API?

**Comment by mojavelinux** [comment] 2019-05-27 19:39
The docname, docfile, and docdir attributes are only set when the input to Asciidoctor is a file. (See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/load.rb#L60-L62). The outfile attribute is only set when Asciidoctor is invoked via convert_file. Otherwise, it's the responsibility of the application to set these attributes (because the processor simply cannot know what the values are).

**Comment by vikram-redhat** [comment] 2019-05-27 21:02
Thanks @mojavelinux! Looking at asciibinder's source code (https://github.com/redhataccess/ascii_binder/blob/master/lib/ascii_binder/engine.rb#L466), I don't think these values are being set.

**Comment by vikram-redhat** [comment] 2019-05-28 01:14
Hmm.. on a closer examination, it is indeed passing a File object when it loads AsciiDoctor: https://github.com/redhataccess/ascii_binder/blob/master/lib/ascii_binder/engine.rb#L455. So, AsciiDoctor should be able to set those values. Not sure if this is a bug in AsciiBinder or AsciiDoctor.

**Comment by mojavelinux** [comment] 2019-05-28 08:35
That code is not passing a File object to Asciidoctor. It's passing a String. That's because it's calling `.read` on the File object. And it's not closing the File object, which is going to lead to memory leaks.

One way to fix the problem is to switch to the load_file method and pass the filename.

```rb
Asciidoctor.load_file topic.source_path, ...
```

Another way would be to use the block form of File.open:

```rb
File.open topic.source_path, 'r' do |topic_file|
  Asciidoctor.load topic_file, ...
end
```

That way, the File is passed to Asciidoctor **and** properly closed.

As a side note, the page attributes should be passed as an Hash of name/value pairs instead of as an array of name=value strings. That way, the values are properly escaped.

**Comment by mojavelinux** [comment] 2019-06-08 07:04
I've opened an issue in AsciiBinder to address the underlying problem. https://github.com/redhataccess/ascii_binder/issues/148

**Closed by mojavelinux** 2019-06-08 07:04 UTC
