### ISSUE TITLE
>=: undefined method `>=' for nil

### ISSUE THREAD

**Issue by jboxman** [asciidoctor/asciidoctor#4046] opened 2021-05-03 03:14 UTC
This originates from:

```
ifeval::[{release} >= 4.5]
```

where `{release}` is not defined anywhere. It builds without any errors when using CLI (`asciidoctor -B . -a toc -d book <file>`), but not with JavaScript:

```js
const asciidocOptions = {
  doctype: 'book',
  // asciidoctor: WARNING: include file is outside of jail; recovering automatically
  //safe: 'server',
  safe: 'unsafe',
  sourcemap: true,
  base_dir: repoDir,
  attributes: {
    icons: 'font',
    toc: 'macro'
  }
}
const doc = adoctor.loadFile(assembly, asciidocOptions);
doc.convert();
```

Is there any option that avoids the exception?

Thanks!

**Comment by mojavelinux** [comment] 2021-05-03 07:13
I have transferred this issue to Asciidoctor core since the same problem exists there and is inherited by Asciidoctor.js

**Comment by mojavelinux** [comment] 2021-05-03 07:15
What this expression resolves to is:

```
ifeval::[nil >= 4.5]
```

If you try to run that in Ruby, you will get a NoMethodError.

For any operation that cannot be run, I think Asciidoctor should resolve the value to false instead of raising an exception.

**Comment by mojavelinux** [comment] 2021-05-03 07:23
There's actually a test for this scenario, but the test uses the `==` operator, which is defined for nil. If the test tried any other operator, it would fail. So it looks like we intended it to work this way, but the test was not robust enough.

**Comment by mojavelinux** [comment] 2021-05-03 07:32
The workaround is to enclose the value in quotes.

```
ifeval::["{release}" >= "4.5"]
```

However, that does slightly change the semantics of the comparison. It may work for your use case, though.

**Comment by jboxman** [comment] 2021-05-03 12:34
> The workaround is to enclose the value in quotes.
> 
> ```
> ifeval::["{release}" >= "4.5"]
> ```
> 
> However, that does slightly change the semantics of the comparison. It may work for your use case, though.

Is it the string comparison rules for JavaScript or Ruby in effect here for the Asciidoctor.js version?

**Comment by mojavelinux** [comment] 2021-05-03 19:07
For these kinds of comparisons, the behavior seems to be the same.

```
"4.0" > "4.5"
false

"4.7" > "4.5"
true
```

**Comment by mojavelinux** [comment] 2021-05-03 19:08
> Is it the string comparison rules for JavaScript or Ruby in effect here for the Asciidoctor.js version?

...and even if the behavior of JavaScript differs from Ruby, the Opal abstraction layer should be normalizing any differences.

**Comment by mojavelinux** [comment] 2021-05-05 06:20
It's pretty easy to reproduce this error even for a defined attribute:

```
ifeval::[{asciidoctor-version} > true]
yep
endif::[]
```

Generally, the policy of Asciidoctor is to not crash as a result of document contents. Therefore, it's consistent with that policy to skip the block when the comparison fails. I don't think a warning is warranted since a failed comparison is a valid outcome.

**Closed** 2021-05-07 05:59 UTC
Labels: bug, compliance

**Comment by jboxman** [comment] 2021-05-10 03:36
@mojavelinux thanks!
