### ISSUE TITLE
wrong `possible invalid reference` warning

### ISSUE THREAD

**Issue by Vampire** [asciidoctor/asciidoctor#3597] opened 2020-03-13 15:39 UTC
- If you define in this file: https://raw.githubusercontent.com/spockframework/spock/spock-1.3/docs/data_driven_testing.adoc
an additional anchor in the top section title like `= [[data-driven-testing]]Data Driven Testing`,
- change the link in https://raw.githubusercontent.com/spockframework/spock/spock-1.3/docs/interaction_based_testing.adoc from `<<data_driven_testing.adoc#,Data Driven Testing>>` to `<<data_driven_testing.adoc#data-driven-testing,Data Driven Testing>>`, and then
- convert the file https://raw.githubusercontent.com/spockframework/spock/spock-1.3/docs/all_in_one.adoc that includes both files above using Gradle plugin `id "org.asciidoctor.jvm.convert" version "3.1.0"` and thus `Asciidoctor 2.0.10`

which is a work-around for #3596 

You now get a warning about `possible invalid reference: data-driven-testing`.
The links work fine.
And you do not get this warning when converting `interaction_based_testing.adoc` on its own.

**Comment by mojavelinux** [comment] 2020-03-14 09:00
It's because of how you are defining the ID. You are defining it in a place that is not cataloged by the referencing system. You need to define the ID on the block itself.

```
[#data-driven-testing]
= Data Driven Testing
```

The way you have it currently defined is an output-only anchor.

This is a duplicate of #3596.

**Closed by mojavelinux** 2020-03-14 09:00 UTC

**Comment by Vampire** [comment] 2020-03-19 09:09
How is this a duplicate of #3596?
#3596 is about the link to the document not being transformed to an anchored link in include.
This issue is about the `possible invalid reference` warning.

So are you saying your documentation is wrong then?
The user manual tells to do it exactly like I did for adding an additional anchor to a section:
![grafik](https://user-images.githubusercontent.com/325196/76998728-d979db80-6955-11ea-9876-dd576523d961.png)
Or did I get something wrongly?

**Comment by mojavelinux** [comment] 2020-03-19 15:32
> So are you saying your documentation is wrong then?

Yes and no. Yes, in an attempt to document how you can define multiple anchors on a section, it's incorrectly implying that all the IDs are referencable in the same way. No in the sense that those other anchors were never intended to be used for the cross referencing system. They are for deep linking only (referenced by a URL fragment). So the documentation should make that clear.

> The user manual tells to do it exactly like I did for adding an additional anchor to a section:

If you want to reference an ID in the xref system, it has to be defined using the primary ID. The auxiliary anchors should be for preserving inbound links only.

> How is this a duplicate of #3596?

Because as far as I can tell it's the same use case described two different ways. I closed this one in order to consolidate the conversation.

**Comment by mojavelinux** [comment] 2020-03-19 15:41
Also keep in mind that the warning is "possible invalid reference". The reason we include the word "possible" (and put this warning behind the verbose flag) is because it means the ID is not in the reference table. In other words, it's not defined in a location where the ID gets scanned (as I described). But we know there are IDs from inline anchors that are not cataloged.

**Comment by Vampire** [comment] 2020-03-19 18:21
Ok, thanks for the clarification.
But then I'd suggest to reopen this issue as doc improvement. :-)

**Comment by mojavelinux** [comment] 2020-03-19 18:56
I would, except I already updated the docs ;)

**Comment by Vampire** [comment] 2020-03-19 19:22
One more question, is there a way to make the `possible invalid reference` message make the Gradle build failing?
Because actually now that I fixed that id-definition, there is no such warning besides if someone mistypes an id and produces a dead link, so it would be nice to be able to fail the build.

**Comment by mojavelinux** [comment] 2020-03-19 19:24
It's proposed. See https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/536
