### ISSUE TITLE
Conflict between stem and inline passtrough when using + in multiple formulas

### ISSUE THREAD

**Issue by MarcdeFalco** [asciidoctor/asciidoctor#3409] opened 2019-09-08 07:43 UTC
There's a conflict between stem and inline passtrough substitution when using at least two formulas with a plus in them.

Minimal example :
`stem:[+] X stem:[+]`
which gets substituted to `stem:[<PASSTROUGH containing ] X stem:[>]`

**Comment by mojavelinux** [comment] 2019-09-09 06:19
Your observation is consistent with how the parser is designed / implemented. That pattern matches the requirements of a constrained passthrough. Thus, the `+` must be escaped. There are various ways of doing so.

* `stem:[\+] X stem:[+]`
* `stem:a[{plus}] X stem:[+]`
* `stem:[+++] X stem:[+]`

These types of problems will be resolved once the design of the inline parser is changed, though that must first be addressed in the AsciiDoc language definition. See #61.

**Comment by jirutka** [comment] 2020-03-06 18:59
One of my users encountered this problem too, in a non-obvious formula: `stem:[+\infty-(+\infty)]`. It behaves even more oddly in asciidoctor.js. I minimalized this example into `stem:[+1+]` – asciidoctor.js renders `0` instead of `+1+` or at least `1`!

This makes Asciidoctor basically unusable for math teachers. I suggest the following easy fix: move [](https://github.com/asciidoctor/asciidoctor/blob/88bc891d6a0143f3a2142f41d29cabe3cb21fe3f/lib/asciidoctor/substitutors.rb#L1105-L1120

**Comment by mojavelinux** [comment] 2020-11-01 22:39
I've added tests to verify the parser is working as designed. See https://github.com/asciidoctor/asciidoctor/commit/e2c0534f1e4d43c716086397ff95caa83afed2a3

I believe the issue with Asciidoctor.js has also since been resolved. It used to have a problem locating passthrough placeholders, which is why the 0 was showing up (technically it was an escaped 0). Regardless, that is/was an issue with Asciidoctor.js, not this project.

**Closed by mojavelinux** 2020-11-01 22:39 UTC
