### ISSUE TITLE
Images inside table do not honor document-wide figure-caption attribute

### ISSUE THREAD

**Issue by jroessel** [asciidoctor/asciidoctor#3448] opened 2019-10-11 13:46 UTC
Example document:

```
.Some image
image::img.png[]

:figure-caption!:

.Some image
image::img.png[]

[cols="a"]
|===
|.This has a caption
image::img.png[]
|:figure-caption!:
.This does not
image::img.png[]
|.Caption again
image::img.png[]
|.No caption
image::img.png[caption=]
|===
```

which results in this rendering:

![image](https://user-images.githubusercontent.com/29534431/66656264-f4755080-ec3d-11e9-9805-3d3c74aff539.png)

My expectation would be that the images within the table would also inherit the (removed) `figure-caption` attribute. It seems to work correctly when _changing_ the attribute to some other value, but unsetting it does not work.

I vaguely recall that Asciidoctor converts table cells with Asciidoc content as a sort of separate document. Perhaps something goes wrong when passing attributes here.

**Comment by mojavelinux** [comment] 2020-02-24 09:39
You are correct. Document attributes that are set in the main document get inherited to the AsciiDoc table cell document. However, document attributes that are unset revert to the default value inside the AsciiDoc table cell. This is not the behavior we expect.

**Comment by mojavelinux** [comment] 2020-02-24 09:41
This is a duplicate of #2586.

**Closed by mojavelinux** 2020-02-24 09:41 UTC
Labels: bug
