### ISSUE TITLE
Asciidoctor does not preserve source file directory structure with --destination-dir

### ISSUE THREAD

**Issue by commonquail** [asciidoctor/asciidoctor#1941] opened 2016-11-21 11:49 UTC
Asciidoctor does not preserve the directory structure of source files when invoked with the `--destination-dir` (`-D`) option.

Consider this sequence of commands:

```sh
$ shopt -s globstar nullglob
$ touch a/a.adoc a/b/{b1,b2}.adoc a/b/c/{a,c}.adoc
$ asciidoctor **/*.adoc
$ tree
$ asciidoctor --destination-dir dist **/*.adoc
$ tree
```

I can appreciate that Asciidoctor may not be intended as a full-fledged build system and that I can achieve this with `make`. However, the Asciidoctor Maven plugin is capable of this (asciidoctor/asciidoctor-maven-plugin#67, asciidoctor/asciidoctor-maven-plugin#99), and although Asciidoctor's behaviour without the `-D` option makes perfect sense the *difference* in behaviour seems inconsistent. At the very least, if this is not desired I think the documentation should reflect the difference, also to answer such questions as what happens if two source files have the same name.

Even if this behaviour is desired I assume `-D` cannot be changed to accommodate it for compatibility, in which case we would need a new option.

**Comment by mojavelinux** [comment] 2016-11-21 20:59
This is a duplicate of #1394. I appreciate the extra insight, so I will link it to that issue to assist with the implementation.

**Closed** 2016-11-23 07:10 UTC
Labels: duplicate
