### ISSUE TITLE
Code blocks leak from table cells

### ISSUE THREAD

**Issue by mmatrosov** [asciidoctor/asciidoctor#3739] opened 2020-08-20 14:29 UTC
Take this `input.adoc`:

    [options="header"]
    |===
    |Recommended |Not recommended
    a|```
    Code snippet 1
    ```
    a|```
    Code snippet 2
    ```
    
    a|```
    Code snippet 3
    ```
    a|
    |===

Compile it:

    asciidoctor input.adoc

See the output `html`:

![image](https://user-images.githubusercontent.com/3617951/90785057-9a87f180-e30a-11ea-876c-48ee970630bd.png)

As you can see, code blocks span below the bottom of table cells. This does not look nice, and distinct code blocks visually merge into one.

**Comment by mojavelinux** [comment] 2020-08-20 19:36
This is a duplicate of #3370, has been fixed in master, and will be corrected in the 2.0.11 release.

**Closed by mojavelinux** 2020-08-20 19:36 UTC
Labels: duplicate
