### ISSUE TITLE
Several footnote problems

### ISSUE THREAD

**Issue by insanetesterftw** [asciidoctor/asciidoctor#1810] opened 2016-07-01 14:04 UTC
Using **Atom** (updated) and **asciidoctor preview** extension (updated) on Windows 7 64. 

![asciidoctor](https://cloud.githubusercontent.com/assets/11148841/16523527/dcb3cd70-3f9b-11e6-9d96-a9397afa00ff.PNG)

https://gist.github.com/insanetesterftw/9acd81da48837e49e87d21f475cc75bc

As you can see, with the exception of the first example, footnotes that contain brackets or sit next to text formatted with italic or negrito are wrong.

**Comment by thmzlt** [comment] 2016-07-03 17:21
Also happens with inline source code.

**Comment by pavs** [comment] 2016-08-12 08:36
This is not related to asciidoctor itself, but to atom preview extension. I am yet to find a good preview extension that works as good as native HTML format. I use a bash script (I am sure also possible in Windows) that looks like this: `ls *.adoc *.css | entr asciidoctor -q *.adoc` it will watch any changes to CSS and adoc file in that specific folder and auto-compile(?) it to HTML format. Then I use http://livereload.com/ to reload the page when the file changes.

I know this doesn't address your issue directly but I think this can be a better approach than using atom preview extension.

**Comment by mojavelinux** [comment] 2016-08-12 08:49
> I think this can be a better approach than using atom preview extension.

The Atom preview extension should convert the document exactly the way Asciidoctor core does (with some minor visual differences due to how the HTML is embedded). That's because the atom preview uses Asciidoctor.js, which is the exact same code base as Asciidoctor core.

**Comment by mojavelinux** [comment] 2016-08-12 08:52
When escaping the square brackets inside an inline macro, you only ever escape the closing bracket. So you should write it as:

```
footnote:[blo [blo\]]
```

**Comment by pavs** [comment] 2016-08-12 08:54
That's weird, up until about 2 weeks ago when I last checked I have found several formatting / rendering issues, that's why I stopped using it. When I get a chance I will give it another go and report any issues [here](https://github.com/asciidoctor/atom-asciidoc-preview).

**Comment by mojavelinux** [comment] 2016-08-12 08:55
Whenever you have problems with formatting getting applied where it shouldn't be, you should switch to unconstrained markup. When you start mixing a lot of formatting marks, there are side effects that happen until we can resolve #61.

Your problems start on this line:

```
_bli_footnote:[_bli_ [bli\].]. *italic continues inside the footnote*
```

I recommend writing it as:

```
__bli__footnote:[_bli_ [bli\].]. *italic continues inside the footnote*
```

**Comment by mojavelinux** [comment] 2016-08-12 08:56
@pavs yes, please report issues. We are still finding errors that are caused by the translation from Ruby to JavaScript, but in theory, if Opal has no bugs, the conversion should be 1-to-1. In other words, we only have to weed out any "lost in translation" errors.

**Comment by mojavelinux** [comment] 2021-02-15 22:54
I believe this issue has been addressed. But even some parts of it still linger, as it's an Asciidoctor.js issue, it should be reported in that project. https://github.com/asciidoctor/asciidoctor.js/ So I'm closing the issue in this repository.

**Closed by mojavelinux** 2021-02-15 22:54 UTC
