### ISSUE TITLE
Footnotes in tables

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor#2350] opened 2017-08-04 21:47 UTC
When I place footnotes in a table with a cell which is `a|`, the footnotes render at the bottom of the cell.

In a normal `|` cell, they render correctly.

This makes a mess of (a) the table and (b) the footnotes. 
This is partly related to #1705 

I am using Asciidoctor 1.5.6.

Any suggestions for a work around other than to not use footnotes in tables?

```asciidoc
|LT9 |Trip Display Point latch a|
SET9 = IN101*IN206*LT8footnote:[A display point is provided since there are no suitable target LEDs.]

RST9 = TRGTR + /IN102

|LED7 |BZ/CBF Enabled |LT8
|DP9 | |LT9
|DP9_1 | |BZ/CBF Trip
|DP9_0 | |NA
|Output 103 |BZ/CBF Main |SV1T + SV2T
|Output 104 |HV CB Trip |RegularTrips + IN101*IN206*LT8
|Output 105 |HV CB CBF Initiate |RegularTrips
|Output 106 |BZ Block |!SV7T*!OUT212footnote:[OUT212 is included for testing purposes using the PULSE command.
Closed contacts cannot be pulsed open if held closed by a logic equation.]
|Output 107 |BZ/CBF Check |SV1T + SV2T
|===
```

![image](https://user-images.githubusercontent.com/674783/28987974-d096089e-79c1-11e7-82fc-193e8aa201cd.png)

![image](https://user-images.githubusercontent.com/674783/28988027-14e304f2-79c2-11e7-942e-b6b4d8c6d08e.png)

**Comment by mojavelinux** [comment] 2017-08-04 22:18
I'm glad to hear you are having a good experience with AsciiDoc!

The behavior you are observing is by design (and, as you mentioned, related to #1705). An AsciiDoc table cell is essentially an embedded document. So the footnotes are meant to be self-contained within the cell.

When I was thinking about this feature when I implemented it, I realized we actually need two types of AsciiDoc table cells. We need lowercase AsciiDoc (a), which just lets you put block-level content in a table cell. We also need uppercase AsciiDoc (A), which acts like a self-contained document. It's currently implemented like uppercase A, so what we're missing is a true lowercase a style.

I'm going to open a separate issue to consider that enhancement as it will solve this and a host of other similar requests.

**Comment by danyill** [comment] 2017-08-04 22:39
Thank you, that sounds like a great idea :smile:

**Comment by tajmone** [comment] 2019-10-28 08:28
@danyill , I've experience the same problem. See my issue:

* tajmone/hugo-book#22

but I've also realized that it's possible to work around this problem in case the cell with the footnote can be styled as `d` (default) instead of `a`. In my case, I had a table where the default style for a column was _AsciiDoc_, but in some places I managed to override it with _default_ instead, thus managing to have the footnotes grouped with the rest of the document notes.

Unfortunately, in some cases the cells required `a` styling due to complex elements (code blocks, etc.) so I couldn't work around them.

Hopefully the new features of #2352 will solve this (and many other table-related problems).

**Comment by VijoPlays** [comment] 2022-08-31 12:16
Is 

> lowercase AsciiDoc (a), which just lets you put block-level content in a table cell

documented somewhere? Wanted to convert a document and needed my table footnotes near the table itself (instead of at the bottom of the entire page), so I'm happy I've found this issue.

If I just missed it: Sorry. If not, might be worth it to add it in the table section.

**Comment by tajmone** [comment] 2022-09-01 06:14
> > lowercase AsciiDoc (a), which just lets you put block-level content in a table cell
>
> documented somewhere?

The `a` is a _style operator_ added to the cell separator (`|`, by default) as part of the  _cell specifier_ (along with positional operators, etc.). For more details see:

- [AsciiDoc Language Documentation] » Tables\:
    + [Add Cells and Rows to a Table]\:
        * [Cell specifiers and operators]
        * [Format Content by Cell]



[Format Content by Cell]: https://docs.asciidoctor.org/asciidoc/latest/tables/format-cell-content/

[Add Cells and Rows to a Table]: https://docs.asciidoctor.org/asciidoc/latest/tables/add-cells-and-rows/
[Cell specifiers and operators]: https://docs.asciidoctor.org/asciidoc/latest/tables/add-cells-and-rows/#specifiers
[AsciiDoc Language Documentation]: https://docs.asciidoctor.org/asciidoc/latest/

**Comment by mojavelinux** [comment] 2023-10-30 21:27
This is a duplicate of #1705.

**Closed by mojavelinux** 2023-10-30 21:27 UTC
