### ISSUE TITLE
when combining table column alignment formats with column- or row spans, alignment styles get applied in a shifted way

### ISSUE THREAD

**Issue by knieriem** [asciidoctor/asciidoctor#3853] opened 2020-11-14 23:10 UTC
When combining table column formatting like centering, left- or right-alignment (e.g. `cols="^,<,>"`) with a few row- or column span specifications, I noticed that in the HTML output sometimes the alignment styles appear shifted: For example, if, in a given row, in the first column I'm defining a cell spanning two rows, then a cell in the second column of the row below gets assigned the alignment of the first column, a cell in the third column the alignment of the second column and so on.

The following example table illustrates the effect, if converted to HTML using asciidoctor (regardless of whether using v1.5.8 or v2.0.12). The affected cells will appear highlighted.

```
[%autowidth,options="header",stripes=none,cols="<,^,>"]
|===
|left-aligned
|centered
|right-aligned

   | l    |  c  |    r
.2+| l    |  c  |    r
          | #c# |   #r#
   | l    |  c  |    r 
 2+| l          |   #r#
   | l .2+|  c  |    r
   | l          |   #r#

|===
```

For comparison, I converted this example table (after stripping some table options) using asciidoc 8.6.10, which doesn't show this behaviour.

Perhaps, when generating a HTML-representation of a table, in rows that contain column- or row spans, the column indices used internally to refer to the column's format definitions could be shifted accordingly so that the correct style gets applied to the following cells.

**Comment by mojavelinux** [comment] 2020-11-14 23:45
This is a duplicate of #989 (and a very well known limitation). You can find advice in that issue (and other linked issues).

Before filing an issue, please search for existing issues to avoid duplicates (unless you already did, in which case disregard this suggestion).

**Closed by mojavelinux** 2020-11-14 23:45 UTC
Labels: duplicate

**Comment by knieriem** [comment] 2020-11-14 23:57
Oh, I'm sorry, I must admit that, in this case, I must have forgotten to search, or I thought I've searched, but did so actually only for my other problem (regarding the former verse table style). What I _did,_ though, is searching the user manual for known limitations in this context, but didn't find them.

**Comment by mojavelinux** [comment] 2020-11-15 02:26
Gotcha. Note that currently the user manual doesn't document these kinds of limitations (it is a bug, albeit a well-known one in the issue tracker). But we'll consider it in the rewrite that's currently underway.
