### ISSUE TITLE
Literal blocks with quotes substitutions lose text in some cases

### ISSUE THREAD

**Issue by Nadreck** [asciidoctor/asciidoctor#4384] opened 2022-11-08 22:31 UTC
**Bug Summary**:

JSON examples in a literal block can get mangled in cases where `quotes` substitutions are allowed, the JSON includes an array, and you add an inline custom style within that array.

**Details**:

 In cases where you have a literal block (regardless of whether you specify it as `source` or a language), with `quotes` as a supported substitution, and the literal block contains JSON with an array, then add an inline style inside that array, any text between the start of the array and the inline style is omitted from the output example.

For example:

```
[subs="+quotes"]
----
{
  "test" : [
    {
      "key" : "[.sampleStyle]##Value1##"
    },
    {
      "key" : "Value2"
    }
  ]
}
----
```

Results in a displayed output of: 
```
{
  "test" : Value1"
    },
    {
      "key" : "Value2"
    }
  ]
}
```

This has been tested in both Antora and in the ruby version of Asciidoctor.

`asciidoctor -v` output:
```
Asciidoctor 2.0.18 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin21]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

A sample .adoc file is attached (extension is .txt because github doesn't like .adoc files):
[sample.txt](https://github.com/asciidoctor/asciidoctor/files/9965738/sample.txt)

**Comment by mojavelinux** [comment] 2022-11-08 22:42
This is a duplicate of #4306 and will be fixed in the upcoming 2.1.0 release. I've even added a test very similar to this case in 7f5d2613b5f3e0fb56e0b352c7bfe305eecb676a.

**Closed by mojavelinux** 2022-11-08 22:42 UTC
