### ISSUE TITLE
Please tag your images on dockerhub with a unique version id

### ISSUE THREAD

**Issue by chess-levin** [asciidoctor/asciidoctor#3504] opened 2019-12-11 15:14 UTC
Hi guys,
I fell in love with Asciidoctor in just one week. Now I try to promote your docker image to my colleges and we were wondering why don't you provide a version tag for each new image you are releasing on dockerhub? https://hub.docker.com/r/asciidoctor/docker-asciidoctor/tags

It is best practice to tag each new version with a unique version tag. It is not reliable to use only latest. There is so much caching going on in a docker cluster, that you never know which version of an image is actually running.
It would be great if you could tag your images.
Thank you for great tool :-)

**Comment by mojavelinux** [comment] 2019-12-11 20:05
This is a duplicate of https://github.com/asciidoctor/docker-asciidoctor/issues/54 (and doesn't pertain to this repository anyway).

**Closed by mojavelinux** 2019-12-11 20:05 UTC
