### ISSUE TITLE
Use <li><span> instead of <li><p> for list items

### ISSUE THREAD

**Issue by bodiam** [asciidoctor/asciidoctor#1346] opened 2015-05-20 12:50 UTC
When rendering lists in AsciiDoctor, a `<p>` is used to render items. This, by default, adds extra lines to pages like Github, and also to the IntelliJ plugin. While it's fixable, having a `<span>` instead would be a fix everywhere. Also, is the `<p>` or `<span>` really needed?

**Comment by mojavelinux** [comment] 2015-05-22 07:15
This is a duplicate of #1087. I explain in that issue why the `<span>` is essential.

> What I discovered when implementing clean room HTML5 for the EPUB3 converter is that if we simply remove the <p> element, it becomes extremely difficult to style both simple and complex lists. We still need some wrapper element around the list item text in order to control spacing. As suggested above, instead of a <p> element, we can use a <span> element so that it does not impact spacing when a dedicated stylesheet is absent.

**Comment by mojavelinux** [comment] 2015-05-22 07:16
I'm going to mark this one as closed since this is covered by #1221 and #1087.

**Closed** 2015-05-22 07:16 UTC
Labels: duplicate

**Comment by bodiam** [comment] 2015-05-22 08:51
Hi @mojavelinux, sorry, I missed that one! Thanks for the comment!

**Comment by mojavelinux** [comment] 2015-05-22 17:18
Not a problem at all. Trust me, I have trouble finding the issues myself
sometimes. Having these cross references helps a lot.

**Comment by cup** [comment] 2020-01-08 03:44
https://github.com/asciidoctor/asciidoctor/issues/1087
https://github.com/asciidoctor/asciidoctor/issues/1221

https://github.com/asciidoctor/asciidoctor/issues/1346
https://github.com/asciidoctor/asciidoctor-pdf/issues/92
https://github.com/asciidoctor/asciidoctor-pdf/pull/164
