### ISSUE TITLE
Keep anchor on header but don't add it to TOC

### ISSUE THREAD

**Issue by facewindu** [asciidoctor/asciidoctor#3755] opened 2020-09-17 12:10 UTC
Is there a way to keep the anchor (and therefore the visual `§` on hover) on headers, but tell asciidoctor to not add them to the TOC ?

I tried `[discrete]`, which removes them from the TOC, but also removes the anchor.

**Comment by mojavelinux** [comment] 2020-09-18 06:47
What you're describing is exactly how it works. Anchors are not added to entries in the TOC. Can you show an example of when the anchor is showing up on a TOC entry?

**Comment by facewindu** [comment] 2020-09-18 08:04
Without `discrete`, I get
![image](https://user-images.githubusercontent.com/5922961/93572537-45391180-f996-11ea-9e9d-86342da86c7d.png)

but also a TOC entry.
What I want is the anchor, but no TOC entry.

**Comment by mojavelinux** [comment] 2020-09-18 08:08
The problem is that you're using an outdated and unsupported version of Asciidoctor that exhibits this bug. It has been fixed long ago. If you upgrade, you will see that this is now fixed.

And you are correct that discrete headings do not show up in the TOC and do not get anchors. There is an open issue to add anchors to discrete headings. See #1997.

**Closed** 2020-09-18 08:09 UTC

**Comment by mojavelinux** [comment] 2020-09-18 08:13
> that exhibits this bug

I had thought you were saying that the anchor showed up in the TOc entry. There were cases when nested `<a>` tags would appear in a TOC entry, which is what I was thinking of. Although that has been fixed, that isn't relevant here.

**Comment by mojavelinux** [comment] 2020-09-18 08:14
> Is there a way to keep the anchor (and therefore the visual § on hover) on headers, but tell asciidoctor to not add them to the TOC ?

Now I understand the question. You want anchors on discrete headings. That is a duplicate of #1997.

**Comment by facewindu** [comment] 2020-09-18 08:16
👍 thanks

**Comment by mojavelinux** [comment] 2020-09-18 08:16
In the meantime, what you can do is extend the converter or customize it using templates. The converter can control all the HTML which is generated, so you use it to add an anchor just like on section titles.

**Comment by mojavelinux** [comment] 2020-09-18 08:19
> The problem is that you're using an outdated and unsupported version of Asciidoctor

So, to clarify, this is not the root cause. But if you are going to file issues, you need to be testing with the supported version of Asciidoctor, which is Asciidoctor 2.
