### ISSUE TITLE
In the manpage backend, URLs are wrapped by default

### ISSUE THREAD

**Issue by aerostitch** [asciidoctor/asciidoctor#2655] opened 2018-04-09 06:51 UTC
Hi,

In https://bugs.debian.org/895187 a user reported that the url are wrapped by default in the manpage backend. I was able to reproduce the issue with the latest version but did not find how to fix it.
Do you have an idea?

Here's the file he used as an example:
```
ASCIIPATIENT(1)
===============

NAME
----
asciipatient - In the manpage backend, URLs are wrapped by default


DESCRIPTION
-----------

Different from the output created by asciidoc, embedded URLs are
happily wrapped across line boundaries. Please change this as this
makes it quite hard to pick them from a terminal.


HOW TO REPEAT
-------------

Run this document through "asciidoctor --backend manpage", then execute
"MANWIDTH=80 man ./asciipatient.1".


EXAMPLE
-------

For details about asciidoctor in Debian, see
https://tracker.debian.org/pkg/asciidoctor

EXPECTED
--------

....
For details about asciidoctor in Debian, see
<https://tracker.debian.org/pkg/asciidoctor>
....


GOT
---

....
For details about asciidoctor in Debian, see <https://
tracker.debian.org/pkg/asciidoctor>
....
```

Here's the command-line he used:
```
asciidoctor --backend manpage
MANWIDTH=80 man ./asciipatient.1
```

Thanks for your help,
Joseph

**Comment by mojavelinux** [comment] 2018-04-14 05:47
This seems to have been resolved by the fix for #2400. I can reproduce in Asciidoctor 1.5.6, but I cannot reproduce using master.

**Closed by mojavelinux** 2018-04-14 05:47 UTC
