### ISSUE TITLE
arbitrary callouts in an image

### ISSUE THREAD

**Issue by sittim** [asciidoctor/asciidoctor#3830] opened 2020-11-06 11:02 UTC
Is it possible to disable the `no callout found` error checking for images where the callouts are in a `png` or `jpg` image, this is so that  something like below can be done?

![image](https://user-images.githubusercontent.com/8825037/98358652-08cc7e00-1ff5-11eb-9aa5-93ab0778878c.png)

When I try to do it, I get the following error:

```
ERROR 2020/11/06 05:56:08 hugo/configuration-links.adoc: asciidoctor: WARNING: <stdin>: line 58: no callout found for <1>
ERROR 2020/11/06 05:56:08 Rebuild failed:

ERROR 2020/11/06 05:56:08 Logged 1 error(s)
INFO 2020/11/06 05:56:08 Received System Events: ["hugo/configuration-links.adoc": CHMOD]
```

**Comment by mojavelinux** [comment] 2020-11-06 11:15
This is a duplicate of #3359. Please add your use case to that issue.

**Closed by mojavelinux** 2020-11-06 11:15 UTC
