### ISSUE TITLE
Asciidoctor user manual link is broken

### ISSUE THREAD

**Issue by harshmadhani** [asciidoctor/asciidoctor#3911] opened 2021-01-11 14:43 UTC
I am trying to open the user manual for Asciidoctor from the homepage, but it seems to be broken. I am trying to open [user manual](https://asciidoctor.org/docs/user-manual) from [home page](https://asciidoctor.org) but it gives 404 error.

![image](https://user-images.githubusercontent.com/1668599/104196115-6ba12200-5449-11eb-8477-373e5e5f89c9.png)

**Comment by Mogztter** [comment] 2021-01-11 16:32
I believe this is related to https://github.com/asciidoctor/asciidoctor.org/commit/b8edd0ac5c349083cc0d75015576c1bfa0969cf9.
The file `docs/user-manual.adoc` was removed and as result the page https://asciidoctor.org/docs/user-manual.html is not generated anymore.

Previously, this page was generated in order to serve a client-side router (JavaScript).

ping @graphitefriction @mojavelinux

**Comment by mojavelinux** [comment] 2021-01-11 18:20
Uh oh!! We're on it!

>

**Comment by mojavelinux** [comment] 2021-01-11 18:41
This is a duplicate of https://github.com/asciidoctor/asciidoctor.org/issues/991, which is now resolved.

**Closed by mojavelinux** 2021-01-11 18:41 UTC
