### ISSUE TITLE
How to get the same HTML structure as from Chrome extension?

### ISSUE THREAD

**Issue by sindzicat** [asciidoctor/asciidoctor#3546] opened 2020-01-21 18:08 UTC
Hello.

Let's say we have the following file:

```
= Title 
:nofooter:
:toc:

++++
<style>
body {
    background-color: #f5f5f5;
    background-image: url(https://cdn.pixabay.com/photo/2016/02/11/01/53/wall-paper-1193001_960_720.jpg);
}

body > #content {
    background-color: white;
    padding: 0.5rem 3rem;
    border: 1px solid #ddd;
    box-shadow: 0 1px 5px #ccc;
    min-width: 400px;
}

/* Заголовки */
h1, h2, h3, h4, h5, h6 {
    color: rgba(0, 0, 0, 0.8);
    font-weight: bold;
}

#content h1 {
    text-align: center;
}
</style>
++++

== Section 1

Some text

== Section 2

Some text
```
When I render this file using asciidoctor.js chrome extension, I get the following HTML structure:

![image](https://user-images.githubusercontent.com/33900895/72830486-e2219e80-3c91-11ea-8b71-6a29b0442467.png)

And page looks good:

![image](https://user-images.githubusercontent.com/33900895/72830511-efd72400-3c91-11ea-8da1-dfb486398e45.png)

When I try Asciidoctor or Asciidoctor.js via Node.js, I got the different HTML structure:

![image](https://user-images.githubusercontent.com/33900895/72830559-054c4e00-3c92-11ea-8c12-136ef0560cf5.png)

And result don't looks so good:

![image](https://user-images.githubusercontent.com/33900895/72830586-139a6a00-3c92-11ea-9dfc-10b7bd6742a0.png)

How can I make Asciidoctor to create the same HTML, as chrome extension?

**Comment by sindzicat** [comment] 2020-01-21 18:10
As for me, header is a part of content, so HTML from extension is more convenient as one from Asciidoctor.

**Comment by mojavelinux** [comment] 2020-01-23 09:19
The answer can be found in the duplicate of this issue: https://github.com/asciidoctor/asciidoctor-browser-extension/issues/314

**Closed by mojavelinux** 2020-01-23 09:19 UTC
