### ISSUE TITLE
SystemStackError when resolving target of xref

### ISSUE THREAD

**Issue by kivikakk** [asciidoctor/asciidoctor#3254] opened 2019-04-11 01:34 UTC
👋  Sorry for the rather anaemic bug report, but I don't have much domain knowledge here.

We've been seeing some `SystemStackError`s appearing in our exception logs originating in AsciiDoctor. I went and found an example that was occurring in a public project so I could share it. I've copied it into a repository of mine so the repro doesn't vanish on us.

Here's the source: https://github.com/kivikakk/what-version-of-asciidoctor-is-github-on/raw/master/_configuration.adoc

(Note that viewing it at https://github.com/kivikakk/what-version-of-asciidoctor-is-github-on/blob/master/_configuration.adoc won't work, as it tries to render it and causes the exception.)

Tested offline:

```console
$ asciidoctor -v
Asciidoctor 2.0.6 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
$ asciidoctor _configuration.adoc
stack level too deep
  Use --trace for backtrace
$ asciidoctor _configuration.adoc --trace
Traceback (most recent call last):
        10577: from /Users/kivikakk/.rbenv/versions/2.5.1/bin/asciidoctor:23:in `<main>'
        10576: from /Users/kivikakk/.rbenv/versions/2.5.1/bin/asciidoctor:23:in `load'
        10575: from /Users/kivikakk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.6/bin/asciidoctor:15:in `<top (required)>'
        10574: from /Users/kivikakk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.6/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
        10573: from /Users/kivikakk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.6/lib/asciidoctor/cli/invoker.rb:111:in `each'
        10572: from /Users/kivikakk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.6/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
        10571: from /Users/kivikakk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.6/lib/asciidoctor.rb:1521:in `convert_file'
        10570: from /Users/kivikakk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.6/lib/asciidoctor.rb:1521:in `open'
         ... 10565 levels...
            4: from /Users/kivikakk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.6/lib/asciidoctor/document.rb:626:in `each'
            3: from /Users/kivikakk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.6/lib/asciidoctor/document.rb:626:in `block (2 levels) in resolve_id'
            2: from /Users/kivikakk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.6/lib/asciidoctor/abstract_block.rb:357:in `xreftext'
            1: from /Users/kivikakk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.6/lib/asciidoctor/abstract_block.rb:279:in `title'
/Users/kivikakk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.6/lib/asciidoctor/substitutors.rb:78:in `apply_subs': stack level too deep (SystemStackError)
$
```

**Comment by mojavelinux** [comment] 2019-04-11 01:41
Thanks for reporting, @kivikakk. I am able to reproduce this locally. I'll track down why this is happening asap and get a fix out. I'll keep you updated.

**Comment by mojavelinux** [comment] 2019-04-11 01:46
The problem is this line:

```
.Run configuration (<<config-image, <image> >>)
```

which can be further reduced to this scenario:

```
[[id]]
.<<does-not-exist>>
text
```

For some reason, when the reference can't be resolved, it keeps trying over and over. But that should give me enough to figure why, fix it, and add a test.

**Comment by mojavelinux** [comment] 2019-04-11 09:07
This crash occurs because, under certain circumstances, the code that initializes the reftexts table invokes the method that initializes the reftexts table. The nested call then tries to initialize the reftexts table again, and down we go. This happens when the xref text of a reference itself contains an xref.

The solution is to give the reftexts table a seed value during initialization, which effectively short-circuits the nested invocations. This is necessary in software engineering when lazy initialization must consider partially constructed entries.

This is safe since once the initialization is complete, the reftexts table will be fully populated. And that's when it gets used.

**Comment by mojavelinux** [comment] 2019-04-12 19:49
A fix is in, but I haven't had a chance to merge it yet because I got pulled away on other tasks. I'll try to have a fix release out this weekend.

**Closed** 2019-04-13 09:16 UTC

**Comment by mojavelinux** [comment] 2019-04-14 11:03
@kivikakk FYI this fix is now available in the 2.0.7 release.

**Comment by kivikakk** [comment] 2019-04-15 05:40
@mojavelinux Thanks! I'll move to get that running.

**Comment by kivikakk** [comment] 2019-04-16 01:08
2.0.7 is now live on github.com! :tada:

**Comment by mojavelinux** [comment] 2019-04-16 02:25
Thank you @kivikakk! You are a :star2:!
