### ISSUE TITLE
Code block in table cell overlaps grid lines

### ISSUE THREAD

**Issue by bobbradley** [asciidoctor/asciidoctor#4141] opened 2021-08-21 19:35 UTC
If a code block is in a table cell, the gray background of the code block overlaps the grid lines. I noticed adding a {sp} after the code block works around it. For example:
```
[cols="4,4"]
|====
a|
----
Test code block 1
----
a|
----
Test code block 2
----
|====

[cols="4,4"]
|====
a|
----
Test code block 1
----
{sp}
a|
----
Test code block 2
----
{sp}
|====

```
<img width="576" alt="Table" src="https://user-images.githubusercontent.com/42216/130333052-5d426245-651a-43f3-9259-53df71f2d013.png">

**Comment by mojavelinux** [comment] 2021-08-21 20:11
This is a duplicate of #3370 and was fixed in the 2.0.11 release. Please upgrade to the latest release of Asciidoctor (currently 2.0.16).

**Closed by mojavelinux** 2021-08-21 20:11 UTC
