### ISSUE TITLE
An option to disable typographic substitutions

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3566] opened 2020-02-11 09:51 UTC
```
"The Cat's Meow" -- a movie by Peter Bogdanovich.
```

will be rendered as 

> "The Cat’s Meow" — a movie by Peter Bogdanovich.

That is, double hyphen will be converted to the em dash; apostrophe will be converted to the curly one; quotation marks are preserved as is.

However, some writers prefer to disable any kind of smart substitutions. That is, they prefer the text to be shown as

> "The cat's meow" - a movie by Peter Bogdanovich.

There are different possible reasons for such kind a desire:

* The writer simply don't like it.
* Search-and-replace issues.
* To avoid issues like "oh, we should use em dash without hyphens in English; en dash with hyphens in Czech; em dash with hyphens in Russian; and yeah, we must use en dashes for number ranges all the way!".

Personally, I would be glad to see such option and I'm sure it is a really good one.

```
:!typographicsubstitutions: // something like this.
```

**Comment by mojavelinux** [comment] 2020-02-11 09:55
This is a duplicate of #1061.

FYI, you can disable replacements per paragraph using:

```
[subs=-replacements]
Cat's
```

**Closed by mojavelinux** 2020-02-11 09:55 UTC
