### ISSUE TITLE
Source code block inside a trable cell overlaps the table border

### ISSUE THREAD

**Issue by joaompinto** [asciidoctor/asciidoctor#3586] opened 2020-03-04 10:13 UTC
It can be reproduced with the following asciidoc document:
```asciidoc
:source-highlighter: highlightjs

[cols="a", options="header"]
|===
| A |
[source, bash]
----
A=1
----
|===
```

Screenshot of the result:
![adoc_table_overlap](https://user-images.githubusercontent.com/1143125/75868879-059b4580-5e09-11ea-8652-ff57a2e0ec5c.png)

**Comment by mojavelinux** [comment] 2020-03-04 10:16
This is a duplicate of an issue which has already been fixed in the upcoming 2.0.11 release.

**Closed** 2020-10-28 10:13 UTC
Labels: duplicate
