### ISSUE TITLE
Enhance lineno API

### ISSUE THREAD

**Issue by ldez** [asciidoctor/asciidoctor#2068] opened 2017-03-11 12:04 UTC
Store the line number for the start of the description list block.

And if possible for list item also.

related to https://github.com/asciidoctor/atom-asciidoc-preview/pull/216

**Comment by mojavelinux** [comment] 2018-05-03 02:43
This is resolved in 1.5.7. As a bonus, you get table cells too.

#2257 was filed as duplicate of this issue, which is where the development notes can be found.

**Closed by mojavelinux** 2018-05-03 02:43 UTC
Labels: duplicate
