### ISSUE TITLE
version 1.5.6 changed generated numbering of section/capters

### ISSUE THREAD

**Issue by a4z** [asciidoctor/asciidoctor#2384] opened 2017-08-23 07:05 UTC
Hi, 
when I generate this document
https://a4z.bitbucket.io/docs/BitBake/guide.html
with version 1.5.6.1, 
all section/chapter numbering is different.
the problem does not occur with 1.5.5, and all other asciidoctor versions I used to generate this document since 2015 worked the same with generating section/chapter numbers.
this is not good.

**Comment by mojavelinux** [comment] 2017-08-23 07:17
Is the source available anywhere? I don't really know what to test without seeing what the source of the document looks like.

**Comment by a4z** [comment] 2017-08-23 08:21
on a private mercurial repository on bitbucket, do you have an account there? Than I could give you access.
If not, where shall I sent/put this docs to, where would you like to have them ?

**Comment by mojavelinux** [comment] 2017-08-24 05:34
Yes, I have a bitbucket account. My username is mojavelinux. Thanks!

**Comment by a4z** [comment] 2017-08-24 08:23
Great!  I have added you as users, you should be able to read the repo, does it work?
a4z/bbtutor
if you want also write permission, or any other info, just tell me
in the adoc folder, there is a guide.adoc that includes 01 to 10.adoc, that makes navigation a lot more easy.
generated via the rake file, since yesterday I use bundle because this doc needs the 1.5.5 version
Thanks!

**Comment by mojavelinux** [comment] 2017-10-24 05:29
I finally got a chance to look into this. You're absolutely right, there is a difference between Asciidoctor 1.5.5 and 1.5.6.x. Starting in 1.5.6, the preface (a section with the style `preface`) is not numbered. This change was proposed and tracked in the following issue: https://github.com/asciidoctor/asciidoctor/issues/2234

The ability to reenable the old behavior has been proposed in #661. Therefore, I'm going to mark this as a duplicate of that issue. What we are looking for there is finalizing the strategy for configuring this behavior.

Another way to solve this problem is to remove the `preface` style from the first section. Since I can see you've done that already, you can safety upgrade to 1.5.6.1 now.

**Comment by a4z** [comment] 2017-10-24 06:40
Thanks a lot @mojavelinux for the info,  your effort and your great work!
I will re-generate the doc  with the latest asciidocotor next weekend.

**Comment by mojavelinux** [comment] 2018-04-07 23:38
I'm going to close this issue as this functionality will be covered/restored by #661.

**Closed by mojavelinux** 2018-04-07 23:38 UTC
Labels: duplicate
