### ISSUE TITLE
Include Content by URI does not support @

### ISSUE THREAD

**Issue by ryandcarter** [asciidoctor/asciidoctor#4327] opened 2022-08-05 17:51 UTC
I am trying to include a file from a url that requires basic auth in the url scheme like so: 

https://bla@raw.githubusercontent.com/opendevise/asciidoc-samples/master/include.adoc

But this does not work:

`include::https://bla@raw.githubusercontent.com/opendevise/asciidoc-samples/master/include.adoc`

And fails with:

`include uri not readable: https://bla@raw.githubusercontent.com/opendevise/asciidoc-samples/master/include.adoc`

URLs without the @ work fine. But I require the @ for authentication.

Is there any solution or workaround to this?

**Comment by mojavelinux** [comment] 2022-08-05 21:16
Asciidoctor does not support including from a URL that requires authentication. This is essentially a duplicate of #3662. You can find a suggested workaround in the comments of that issue. https://github.com/asciidoctor/asciidoctor/issues/3662#issuecomment-635542901 Another approach is to implement a custom include processor. See https://docs.asciidoctor.org/asciidoctor/latest/extensions/include-processor/

In the future, please direct questions about usage to the project chat at https://chat.asciidoctor.org.

**Closed by mojavelinux** 2022-08-05 21:16 UTC
