### ISSUE TITLE
Inconsistent expansion of user-defined attributes inside section titles.

### ISSUE THREAD

**Issue by PauloFrancaLacerda** [asciidoctor/asciidoctor#3202] opened 2019-03-24 14:49 UTC
The following examples work normally with v1.5.8. After upgrading to v2.0.0, it's broken.
NOTE: The source-code is the minimum to reproduce the problem.

  . Case 1: [adoc](https://blaisepoint.com/tests/adoc_2_case_01.adoc) results with Asciidoctor [1.5.8](https://blaisepoint.com/tests/adoc-158/adoc_2_case_01.html) and [2.0.0](https://blaisepoint.com/tests/adoc-200/adoc_2_case_01.html)
  . Case 2: [adoc](https://blaisepoint.com/tests/adoc_2_case_02.adoc) results with Asciidoctor [1.5.8](https://blaisepoint.com/tests/adoc-158/adoc_2_case_02.html) and [2.0.0](https://blaisepoint.com/tests/adoc-200/adoc_2_case_02.html)
  . Case 3: [adoc](https://blaisepoint.com/tests/adoc_2_case_03.adoc) results with Asciidoctor [1.5.8](https://blaisepoint.com/tests/adoc-158/adoc_2_case_03.html) and [2.0.0](https://blaisepoint.com/tests/adoc-200/adoc_2_case_03.html)

Not sure, but it looks like the engine goes into an inconsistent state (regarding user-defined attributes) as soon as it finds a *blank line*.

I've been noticing this peculiarity (about blank lines vs attributes) since older versions but, in v2.0, this is now way harder to workaround.

**Comment by mojavelinux** [comment] 2019-03-24 20:43
:scream: 

I see what's going on. The problem is not the blank lines. It has to do with when section titles get resolved.

What caused this is a change to how we store references (see https://github.com/asciidoctor/asciidoctor/issues/3084). Prior to 2.0.0, we resolve the title when the line is first read and store that in the catalog. That would grab any attributes defined at that line and apply them. Later, when the title is used, the attributes have already been resolved. Now, we store the node without resolving the title first. Hence, when the title is later resolved, it's happens "out of context".

The simple solution to this problem is to eagerly resolve the title if it contains an attribute reference. That would resolve the previous behavior. I can do that for 2.0.1.

Long term, we need to get rid of this whole "attribute playback system" and actually store the document attributes with the nodes. That way, no matter where you use the node, it will have all the information with it that was present at that location in the document. That's this issue: https://github.com/asciidoctor/asciidoctor/issues/692#issuecomment-188717649 It's something I'd really like to address in the next major version, if possible.

**Comment by elextr** [comment] 2019-03-24 21:03
The best solution to attributes is to treat them like variable names are treated in programming languages, the attribute name has a scope, and it can be hidden by new definitions of the name during their scope.  This also allows attributes to have specific values for include files without affecting the including file.

These features are then solved problems using normal compiler symbol table technologies.

**Comment by PauloFrancaLacerda** [comment] 2019-03-24 21:19
Excellent! I'm looking forward to v2.0.1.  :)

**Comment by mojavelinux** [comment] 2019-03-24 21:59
@elextr The problem was introduced long ago in the translation from AsciiDoc Python's streaming processor to Asciidoctor's AST-based one. At the time, I should have stored the attributes in the AST. I didn't, opting instead to "play them back" as the tree is walked. In hindsight, that was a mistake. Until we solve that issue (#692), the only reasonable way to handle the attributes in references is to resolve them eagerly.

**Comment by PauloFrancaLacerda** [comment] 2019-03-24 22:03
I'd also suggest you to add a test case to `attributes_test.rb` to check against this issue.

**Comment by mojavelinux** [comment] 2019-03-24 22:11
> I'd also suggest you to add a test case to attributes_test.rb to check against this issue.

Oh, you better believe it (though it would be in sections_test.rb).

**Comment by elextr** [comment] 2019-03-24 23:09
@mojavelinux for sure its not something to do in a minor bugfix version, it needs to be in a major version since it may act differently in some edge cases.  

My comment was more directed at the comment you linked above about storing them in the AST, thats fine but you also need a fast way of finding them, walking the AST to find attributes is going to be slow.  Looking up how compilers do it might save you some effort of inventing your own.

**Comment by mojavelinux** [comment] 2019-03-25 06:03
@elextr We're getting off topic here for something that should be discussed in #692. Of course they should be easy to find. In that issue, I describe that what I mean is to reify them so that they are part of the node.

**Comment by elextr** [comment] 2019-03-25 06:23
:man_shrugging: just trying to suggest a source of prior art to save you some effort, maybe I shouldn't bother.

To be clear your comment before my first one references a specific comment of #692, not the whole issue, so thats what I read and commented on.

**Comment by mojavelinux** [comment] 2019-03-25 06:41
I'm not saying I don't welcome your feedback. But you're expanding the discussion for a very specific bug into something that just can't be solved here.

**Comment by mojavelinux** [comment] 2019-03-25 06:44
@PauloFrancaLacerda To provide a bit more context, this has everything to do with the table of contents. When we store the nodes without eagerly resolving the title, then they get resolve for the first time in the table of contents where they are divorced from the attributes they reference. That's why disabling the toc resolves the issue (when using 2.0.0).

You'd see the same problem if you referenced a later section in an earlier one (a forward reference). Again, it would resolve the title in a different context.

**Closed** 2019-03-25 11:23 UTC
Labels: bug, v2.0.1

**Comment by PauloFrancaLacerda** [comment] 2019-03-25 11:35
> ......That's why disabling the toc resolves the issue (when using 2.0.0).

@mojavelinux, That's ok as a workaround but, unfortunately, disabling the TOC is not an option for me; it's crucial for some of my (huge) docs. 
I'll stick to v1.5.8 until the issue is actually addressed.

**Comment by mojavelinux** [comment] 2019-03-25 11:50
Of course, I was only giving you background so you could better understand what was happening.

2.0.1 is out.

**Comment by PauloFrancaLacerda** [comment] 2019-03-25 13:29
> 2.0.1 is out.

WOW! Such a great surprise!
I can confirm the bug is gone.
Thank you!  :1st_place_medal:

**Comment by mojavelinux** [comment] 2019-03-25 17:26
@PauloFrancaLacerda Thank *you* for verifying and providing the test cases. I really appreciate it! Go team!

**Comment by PauloFrancaLacerda** [comment] 2019-03-25 19:12
> Thank _you_ for verifying and providing the test cases. I really appreciate it! Go team!

It's a great honor for me to participate and help as possible. This is an extremely useful product. I use it in a daily basis. In fact, my professional work couldn't survive today without Asciidoctor.
I'm really glad to help.  :)
