### ISSUE TITLE
Missing Border in Multirow-Cell

### ISSUE THREAD

**Issue by Baerbeisser** [asciidoctor/asciidoctor#2563] opened 2018-02-16 20:47 UTC
With Asciidoctor 1.5.6.1 in Manjaro, if i create a Table with Cells that spann multiple rows, each second Cell has no right border.

```a
Schedule
========
Testcase

[cols=">1h,^.^4,^.^4",options="header"]
|====
|           |Day 1       |Day 2
|08:00   .2+|Task 1   .4+|Task 4
|09:00
|10:00   .2+|Task 2
|11:00
|12:00    2+|*Lunchhour*
|13:00   .4+|Task 3   .4+|Task 5
|14:00
|15:00
|16:00
|17:00
|====
```
becomes:
![schedule](https://user-images.githubusercontent.com/22264628/36327629-08667838-1357-11e8-9e92-e6e85ba3d422.png)

The reason lies in
```html
table.grid-all>*>tr>.tableblock:last-child,table.grid-cols>*>tr>.tableblock:last-child{border-right-width:0}
```
"border-right-width" should be 1px instead of 0.

This behavior does not appear in Asciidoc and Asciidoctor-PDF.
Weirdly, it appears in [AsciidocLive](https://asciidoclive.com/) too (does it use Asciidoctor instead of Asciidoc?)

I dunno how to fix that, except in the HTML-File itself. But it seems easily fixable.

**Comment by mojavelinux** [comment] 2018-05-03 01:37
> it appears in AsciidocLive too (does it use Asciidoctor instead of Asciidoc?)

Yes. It uses Asciidoctor.js.

**Comment by mojavelinux** [comment] 2018-05-03 01:42
Unfortunately, this is extraordinarily hard to fix without a hint in the HTML. That rule is there to prevent a double border on right-most column. But when there are rowspans, this assumption breaks down because the last cell in a row is not necessarily in the right-most column. AsciiDoc Python doesn't have this issue since it is sloppy about the borders.

**Comment by hkp-wcd** [comment] 2019-02-26 09:38
We had the same issue. I removed this rule from the default stylesheet:
```
table.grid-all>*>tr>.tableblock:last-child, table.grid-cols>*>tr>.tableblock:last-child {
    border-right-width: 0;
}
```

And to avoid the double border I added:
```
table.grid-all { 
    border-collapse: collapse;
}
```

This fixed the issue.

**Comment by Baerbeisser** [comment] 2020-02-22 20:24
@mojavelinux 
I just saw, that this issue is still open.
The commit of hkp-wcd is applied only on his own fork.
Would `table.grid-all { border-collapse: collapse; }` break anything?

**Comment by mojavelinux** [comment] 2020-10-27 23:32
The border-collapse has been removed by #3793.

While the other part of the proposed changed would fix this issue, I believe that ultimately the solution for #3387 will solve this problem (at least when using the default frame=all,grid=all and other compatible combinations).

What I'll do is apply the proposed patch. Then, I'll continue on with #3387.

**Comment by mojavelinux** [comment] 2020-10-28 10:09
I've confirmed #3387 will solve this case, so I'm going to close it as a duplicate. Please follow that issue instead.

**Closed** 2020-10-28 10:13 UTC
Labels: duplicate

**Comment by acromarcopolo** [comment] 2022-12-16 10:58
alas this is still an issue in https://asciidoclive.com/ and in VS Code's AsciiDoc from asciidoctor

**Comment by ni4** [comment] 2024-04-18 13:07
+1, still see this in VS Code/asciidoclive.

**Comment by mojavelinux** [comment] 2024-04-18 18:52
That just means the stylesheet being used there is not up to date.

In the future, please direct comments to the project chat at https://chat.asciidoctor.org.
