### ISSUE TITLE
Wrong out put for tables with vertical headers and span

### ISSUE THREAD

**Issue by anotherandi** [asciidoctor/asciidoctor#3850] opened 2020-11-11 11:05 UTC
Hallo,

when I convert the following adoc fragment with a table that uses vertical headers and cells spanning multiple rows.
[cols="1h,4a"]
|===
| A | a1
| B | b1
.3+| C
| c1
| c2
| c3
| D | d1
|===

In html I would expect the cells containing A, B and C to be <th> all others should be <td>.
But instead the cells c2 and c3 are also <th> elements resulting in incorrect stylings of the table. (e.g. bold text for a non heading cell)

May be related to #738

Thank you,
Andi

BTW, Thank you to all contributors, for this fantastic tool.

**Comment by mojavelinux** [comment] 2020-11-11 11:21
You're welcome.

Yes, this is a limitation of colspecs when combined with colspans. You need to mark up the table as follows:

```asciidoc
[cols="1h,4a"]
|===
| A | a1
| B | b1
.3+| C
| c1
d| c2
d| c3
| D | d1
|===
```

This isn't related to #738, but rather a duplicate of #989.

**Closed** 2020-11-11 11:22 UTC
Labels: duplicate

**Comment by anotherandi** [comment] 2020-11-11 11:26
Is it also correct to add the d| in front of c1. Well it works and it is easier to generate. But can I rely on it?

**Comment by mojavelinux** [comment] 2020-11-11 12:23
Yep. I was just demonstrating the minimal example. You can put a style on
any cell.
