### ISSUE TITLE
Improve footnotes (html) - Word Joiner Unicode code point

### ISSUE THREAD

**Issue by fekir** [asciidoctor/asciidoctor#4355] opened 2022-09-18 18:46 UTC
I just happened to observe what is described in this article, unfortunately I do not have an  example to show.

https://ramshankar.org/blog/posts/2020/typographically-correct-footnotes-in-asciidoctor/

The TLDR; is that the browser might split the text from its the footnote marker, and this can be prevented manually by adding the "Word Joiner Unicode code point": `{wj}`

It is a trivial fix, but it is easy to forget to add such invisible character as

 * the issue is not always easy to reproduce (depends on the environment)
 * it is an invisible character

Also the article explains that actually the footnote marker itself could be splitted. So to be sure, one needs to add multiple `{wj}`.

I think it would make much more sense if asciidoctor would add by himself such character automatically, as least for HTML. I do not know if other output formats have similar issue, but I suspect so.

**Comment by mojavelinux** [comment] 2023-11-02 07:44
This is a duplicate of #3467.

**Closed by mojavelinux** 2023-11-02 07:44 UTC
