### ISSUE TITLE
CSV table with AsciiDoc column style throws NoMethodError

### ISSUE THREAD

**Issue by Bartimmermans** [asciidoctor/asciidoctor#2835] opened 2018-08-07 14:39 UTC
I am using AsciiDoctor 1.5.7.1. My document contains a CSV table, for which one of the columns is configured with the AsciiDoc style (marked with 'a' in my column description), independent of the fact that the column actually contains AsciiDoc or not (in below example, it does not).

### test.adoc
```
= Title

[format="csv",width="100%",cols="<50,<50a",options="header"]
|===
include::_table.csv[]
|===
```

### _table.csv
```
Column 1, Column 2
Value 1, Value 2
```

I now try to convert my document using the docbook5 backend.

```
asciidoctor -b docbook5 test.adoc
```

Following exception is thrown.
```
NoMethodError: undefined method `convert' for nil:NilClass
                content at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/lib/asciidoctor/table.rb:345
         block in table at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/docbook5.rb:431
                   each at org/jruby/RubyArray.java:1733
         block in table at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/docbook5.rb:419
                   each at org/jruby/RubyArray.java:1733
         block in table at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/docbook5.rb:417
                   each at org/jruby/RubyArray.java:1733
                  table at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/docbook5.rb:413
                convert at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/base.rb:38
                convert at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:71
       block in content at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:80
                    map at org/jruby/RubyArray.java:2485
                content at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:80
                content at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/lib/asciidoctor/document.rb:1209
               document at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/docbook5.rb:36
                convert at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/base.rb:38
                convert at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/lib/asciidoctor/document.rb:1141
                convert at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1515
  block in convert_file at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589
                   open at org/jruby/RubyIO.java:1141
           convert_file at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589
       block in invoke! at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/lib/asciidoctor/cli/invoker.rb:129
                   each at org/jruby/RubyArray.java:1733
                invoke! at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/lib/asciidoctor/cli/invoker.rb:112
                 <main> at C:/Program Files/JRuby/jruby-9.1.7.0/lib/ruby/gems/shared/gems/asciidoctor-1.5.7.1/bin/asciidoctor:14
                   load at org/jruby/RubyKernel.java:979
                 <main> at C:\Program Files\JRuby\jruby-9.1.7.0\bin\asciidoctor:22
```

Note that this worked perfectly fine in AsciiDoctor 1.5.6.2. The issue occurred while upgrading to 1.5.7.1. I found out that when leaving out the 'a' in the column description, the issue doesn't occur anymore, but of course, in my case, the table does contain some AsciiDoc style.

**Comment by mojavelinux** [comment] 2018-08-24 05:56
This is a duplicate of #2817. A fix will be included in 1.5.8 (or perhaps 1.5.7.2 if we decide to publish another micro-patch release).

**Closed** 2018-08-24 05:56 UTC
Labels: duplicate
