### ISSUE TITLE
AsciiDoc lists have extra space (when compared to Markdown output)

### ISSUE THREAD

**Issue by sgilda** [asciidoctor/asciidoctor#1087] opened 2014-09-11 20:52 UTC
I am converting Markdown files to Asciidoc. Simple lists render strangely using Asciidoctor.

This is the source:

This is a list:
- Item 1
- Item 2
- Item 3

Asciidoctor renders list items with a  `<p></p>` tag and the resulting list has blank lines between
list items, resulting in a very spread out list.

The resulting HTML rendered by Asciidoctor:

```
            <div>
                <p>This is a list:</p>
            </div>
            <div>
                <ul>
                    <li>
                        <p>Item 1</p>
                    </li>
                    <li>
                        <p>Item 2</p>
                    </li>
                    <li>
                        <p>Item 3</p>
                    </li>
                </ul>
            </div>
```

Markdown files render more compactly like this: 

```
            <ul>
                <li>Item 1</li>
                <li>Item 2</li>
                <li>Item 3</li>
            </ul>
```

**Comment by gAmUssA** [comment] 2015-02-13 16:33
@mojavelinux What's min required css should be included to fix this "bug"?

**Comment by odoepner** [comment] 2015-02-16 04:38
I noticed the same issue when migrating my READMEs from md to adoc. Any idea when you will start using <span> instead of <p> ?

**Comment by mojavelinux** [comment] 2015-04-01 17:25
I have it scheduled for 1.6.0. The default Asciidoctor stylesheet provides the CSS necessary to make it render more compact. However, it's going to look expanded on GitHub until the HTML changes because GitHub doesn't (and won't likely) provide the necessary styles. But hey, they could surprise us :)

**Comment by wimdeblauwe** [comment] 2015-04-30 10:04
+1 for this. I also find the lists too "spread out" when converting to HTML.

**Comment by mojavelinux** [comment] 2015-10-27 05:35
Also related to #1221.

**Comment by odoepner** [comment] 2016-05-23 20:19
I don't to nag, but is there any progress on this issue? :)

**Comment by mojavelinux** [comment] 2016-05-23 21:44
Not yet, though we've now implemented the solution in two other converters (epub3 and bespoke). The technical work is now done. It's just a matter of porting this over.

For reference, see https://github.com/asciidoctor/asciidoctor-bespoke/blob/976f63e184a020596f13a19b890ac4bfc5a23356/templates/slim/ulist.html.slim#L3-L8

**Comment by odoepner** [comment] 2016-05-24 02:36
Thanks for the quick response, Dan.

**Comment by mojavelinux** [comment] 2016-05-28 22:35
Here's the proposed structure for an unordered list expressed as a Slim template:

```slim
- if title?
  figure.list.unordered id=id
    figcaption=title
    ul class=[style, role]
      - items.each do |_item|
        li
          span.primary=_item.text
          - if _item.blocks?
            =_item.content
- else
  ul id=id class=[style, role]
    - items.each do |_item|
      li
        span.primary=_item.text
        - if _item.blocks?
          =_item.content
```

Drop this file into the the templates directory as `ulist.slim.html`, then pass the templates directory to Asciidoctor when you invoke it (`template_dir` option for API, `-T` option for CLI).

**Comment by mojavelinux** [comment] 2016-05-28 22:35
Note, the use of the figure container element may be deferred the built-in HTML converter is migrated to HTML5 semantic elements. But you get the idea.

**Comment by odoepner** [comment] 2016-05-28 23:54
Hm, and how would I use this for the README.adoc files of my github
projects?

On Sat, May 28, 2016 at 7:35 PM, Dan Allen <notifications@github.com> wrote:

> Note, the use of the figure container element may be deferred the built-in
> HTML converter is migrated to HTML5 semantic elements. But you get the idea.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/asciidoctor/asciidoctor/issues/1087#issuecomment-222332820>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABdyE8wW4m1_11DU-0seuWbPn6_qBwRCks5qGMNJgaJpZM4ChLpy>
> .
>



-- 
🐭 🐮 🐱 🐵
Oliver Doepner
http://oliver.doepner.net/

**Comment by mojavelinux** [comment] 2016-05-29 01:06
@odoepner sorry, that's not possible at the moment because GitHub does not allow the use of any AsciiDoc extensions. But given how minor this change is, I think we can get it into core in the next release so it's available once GitHub upgrades (though we have no idea when that would be).

**Comment by odoepner** [comment] 2016-05-29 03:46
That would be great. Thanks, Dan. :)

On Sat, May 28, 2016 at 10:06 PM, Dan Allen <notifications@github.com>
wrote:

> @odoepner <https://github.com/odoepner> sorry, that's not possible at the
> moment because GitHub does not allow the use of any AsciiDoc extensions.
> But given how minor this change is, I think we can get it into core in the
> next release so it's available once GitHub upgrades (though we have no idea
> when that would be).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/asciidoctor/asciidoctor/issues/1087#issuecomment-222336950>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABdyE6r2woWeZN3NBGrrKiqCiz_zQfypks5qGOaegaJpZM4ChLpy>
> .
>



-- 
🐭 🐮 🐱 🐵
Oliver Doepner
http://oliver.doepner.net/

**Comment by mwalburn** [comment] 2016-11-02 22:42
@mojavelinux I'm running into this as well, but dropping the slim template in and passing the template directory with `-T` doesn't seem to be working. Any other ideas or updates?

This is the command I'm using to process my asciidoc:

```
asciidoctor -a stylesheet! --template-dir=~/Dropbox/development/asciidoc-templates/ 01-00-market-positioning.asc -o -
```

Thanks!

**Comment by mojavelinux** [comment] 2016-11-22 08:16
@mwalburn Put the slim template directly in the folder you are referring to.

(If the template is in a subfolder named "slim", then you need to add the `-E slim` option flag to the asciidoctor command).

**Comment by mojavelinux** [comment] 2019-05-03 22:09
I really think this could be done before we overhaul the default HTML converter.

**Comment by sgilda** [comment] 2019-05-11 14:41
That would be great!

**Comment by t0rb1t** [comment] 2019-09-27 15:54
Any update on how to make lists less spaced out? I love Asciidoc, but I really don't like how the lists are displaying.

**Comment by mojavelinux** [comment] 2019-09-27 23:20
As I've said numerous times, all the HTML that Asciidoctor generates can be changed. You can find an example here: https://github.com/asciidoctor/jekyll-asciidoc#step-5-compose-a-template

It's very unlikely this will change in the current converter (though don't hold me to that). It will definitely be changed in the new semantic HTML converter. See #242.

**Comment by cup** [comment] 2020-01-08 03:43
https://github.com/asciidoctor/asciidoctor/issues/1087
https://github.com/asciidoctor/asciidoctor/issues/1221
https://github.com/asciidoctor/asciidoctor/issues/1346
https://github.com/asciidoctor/asciidoctor-pdf/issues/92
https://github.com/asciidoctor/asciidoctor-pdf/pull/164

**Comment by pastelmind** [comment] 2020-01-21 13:07
There's a similar issue with `<p>` tags inserted in `<td>` tags, which makes tables way taller than they should be.

Until the issue is resolved, you can use a bookmarklet that removes the extra margins. Copy the following line, create a bookmark, and paste the line in the URL field:

```
javascript:document.body.appendChild(document.createElement('style')).textContent='li>p:only-child,td>p:only-child{margin:0}';void(0);
```

This bookmarklet inserts a `<style>` tag in the current page which removes the extra margins. While viewing an AsciiDoc-based page on GitHub, click the bookmarklet to activate it.

**Comment by cup** [comment] 2020-03-02 02:43
If anyone can implement this, I am willing to donate $800.

**Comment by Mogztter** [comment] 2020-03-02 07:02
@cup what is your requirement? there are a few solutions to fix this issue:

- create a custom converter (to not wrap item elements in a `<p>` element)
- custom stylesheet to reduce the space (visually)
- update the default HTML5 converter

**Comment by cup** [comment] 2020-03-02 13:04
@Mogztter it is a challenge, because a proper resolution would look like this:

1. Submit PR to updated the default HTML5 converter
2. PR merged
3. New gem with this fix is released
4. Submit PR with new gem to <https://github.com/github/markup>
5. PR merged

All that will be difficult, because even if someone does number one, it might
not get merged, and even if it is merged, number five might not get merged.
Regarding the specifics, unless an alternative argument is made, I think
AsciiDoc should do what CommonMark does:

> A list is **loose** if any of its constituent list items are separated by
> blank lines, or if any of its constituent list items directly contain two
> block-level elements with a blank line between them. Otherwise a list is
> **tight**. (The difference in HTML output is that paragraphs in a loose list
> are wrapped in `<p>` tags, while paragraphs in a tight list are not.)

https://spec.commonmark.org/0.29#loose

So this:

~~~md
- Sunday
- Monday
~~~

should produce this or similar:

~~~html
<ul>
   <li>Sunday</li>
   <li>Monday</li>
</ul>
~~~

If just number one is completed, I am willing to donate $600.

**Comment by Mogztter** [comment] 2020-03-02 13:51
Alright!
I'm willing to work on it but first I need to hear from @mojavelinux to know where he stands: 

"I really think this could be done before we overhaul the default HTML converter."

"It's very unlikely this will change in the current converter (though don't hold me to that). It will definitely be changed in the new semantic HTML converter. See #242."

As you might have heard, the formation of the AsciiDoc Working Group is in progress. Since the Asciidoctor project will be contributing language documentation (ie. user manual) and tests to the AsciiDoc Working Group, it might not be the perfect time to make this change (even if it sounds reasonable).
Arguably, it won't affect the syntax but my understanding is that the specification will also include a DOM (Document Object Model).

> All that will be difficult, because even if someone does number one, it might
not get merged, and even if it is merged, number five might not get merged.

It's true that historically GitHub has been "slow" to upgrade to the latest version of Asciidoctor but they are now updating at a much faster pace (even though GitHub is currently running 2.0.7 and not 2.0.10).

> If just number one is completed, I am willing to donate $600.

I think you need at least number one and two completed. I doubt that GitHub will accept to use a custom converter or a fork version of Asciidoctor. So if your goal is to see this change on GitHub in a near future you should aim for a merged pull request in Asciidoctor.

**Comment by cup** [comment] 2020-03-02 13:57
@Mogztter I agree, so ideally all five steps complete, but failing that number one and two. Thank you!

**Comment by mojavelinux** [comment] 2020-03-02 18:53
Before this thread continues, I want to address the current framing. While I'm in full support of compensating someone for the time and effort they put into a solution, I want to be very clear that solutions cannot simply be bought. That sets a very dangerous precedent and not what an open source project is about. Solutions should be go through the process of making a strong case for, discussing and agreeing on a design / path that respects the constraints of our compatibility goals, and finally someone submitting code that implements the proposed change. Not because prize money has been floated. That's just not how this works.

**Comment by mojavelinux** [comment] 2020-03-02 19:07
As I've already stated, this change cannot go into the current HTML converter. There are too many published works that rely on the HTML output with its default stylesheet such that changing a core structure would create a very complex situation, even if done in a major version. (If someone is able to demonstrate how we can ensure a smooth transition, I'd be willing to reconsider my stance).

The correct solution, as I've already stated, is to press forward with #242. (I agree that it's not moving forward fast enough, so I'm open to being pushed).

The other solution is to add an extended converter to github/markup that overrides the `convert_ulist` and `convert_olist` methods to switch from a `<p>` to a `<span>` for the primary list text. (GitHub is free to use whatever converter they choose, esp since they mostly allow it to render as is, without styles). Since Asciidoctor 2, extending the converter in Ruby is very straightforward. Barring that solution, another is to get GitHub to add styles that remove the default margin on the first `<p>` like the default stylesheet does.

As for the point about the AsciiDoc specification, I'm not sure it's that relevant in this case. The spec is about parsing the AsciiDoc. Besides, it will still a long time before something comes out of that. But regardless, the output produced from AsciiDoc is designed to be flexible and does not limit what we can produce. The concern in Asciidoctor is compatibility with existing uses.

**Comment by cup** [comment] 2020-03-02 19:17
I mean no disrespect, these days I am just busy with other programming projects.
So while I might be able to work up a Pull Request myself, at this point I have
more free money than free time.

If the issue was to be resolved, I have no concerns regarding licensing. Any
code that is submitted, can use any license that the author or project
maintainer want to put on it. I merely want the problem to be resolved for
myself, and for anyone who dislikes the current behavior with regard to this
issue. I see this page:

https://asciidoctor.org/docs/asciidoc-syntax-quick-reference

and I know much work went into making all that happen, and I think AsciiDoc is
a great tool, but until this issue is resolved I hesitate to use the tool.
Thanks for understanding.

**Comment by mojavelinux** [comment] 2020-03-02 20:28
Understood. Thanks for clarifying your position and situation!

**Comment by Mogztter** [comment] 2020-03-02 21:13
> Before this thread continues, I want to address the current framing. While I'm in full support of compensating someone for the time and effort they put into a solution, I want to be very clear that solutions cannot simply be bought. That sets a very dangerous precedent and not what an open source project is about. Solutions should be go through the process of making a strong case for, discussing and agreeing on a design / path that respects the constraints of our compatibility goals, and finally someone submitting code that implements the proposed change. Not because prize money has been floated. That's just not how this works.

Of course not, but my understanding was that it was something that we planned to do in the future semantic converter right?
So, if someone is willing to financially support a "planned change" and someone is willing to work on it (ie. propose, discuss, design and implement a solution while respecting the constraints and compatibility goals) then I think it's fine no?

That's why I asked Steven about his requirement and I asked you about your position. I wanted to make sure that it was indeed something that Asciidoctor was considering to implement in a near future. You wrote:  "I really think this could be done before we overhaul the default HTML converter.". I read it as: "it could be done in Asciidoctor core before overhaul the default HTML converter".
Also, Steven requirement could have been to produce an HTML outside of GitHub then it would have been a custom converter (ie. outside of Asciidoctor core).

Anyway, in this case, the requirement is to make this change available on GitHub.

> As I've already stated, this change cannot go into the current HTML converter. (If someone is able to demonstrate how we can ensure a smooth transition, I'd be willing to reconsider my stance).
> The correct solution, as I've already stated, is to press forward with #242 (a new converter with a new stylesheet). (I agree that it's not moving forward fast enough, so I'm open to being pushed).

Creating a new semantic converter comes with a lot of questions and decisions. Speaking of which, I do have a pull request to convert a paragraph using semantic constructs: https://github.com/asciidoctor/asciidoctor/pull/3418 (with a few questions).

Maybe we could progressively introduce "semantic constructs" that could be enabled using one or more opt-in options/attributes? It would help ensure a smooth transition and we will also get early feedback from the users so we can refine the semantic converter.

For instance, I could decide to use semantic constructs for lists and paragraphs using `:asciidoctor-semantic-list:` and `:asciidoctor-semantic-paragraph:` (don't pay too much attention to the naming).

> There are too many published works that rely on the HTML output with its default stylesheet such that changing a core structure would create a very complex situation, even if done in a major version.

I'm more concern about custom stylesheet. If we control both the HTML output and the stylesheet then I think it's possible to create a visually "backward compatible" output.
But if we don't then it could cause issues even if we just replace the `<p>` element with a `<span>` element. For instance, if someone is using a custom style on `li > p`.

> The other solution is to add an extended converter to github/markup that overrides the convert_ulist and convert_olist methods to switch from a <p> to a <span> for the primary list text. (GitHub is free to use whatever converter they choose, esp since they mostly allow it to render as is, without styles). Since Asciidoctor 2, extending the converter in Ruby is very straightforward. Barring that solution, another is to get GitHub to add styles that remove the default margin on the first <p> like the default stylesheet does.

Why not but this "issue" is not limited to GitHub right?

> As for the point about the AsciiDoc specification, I'm not sure it's that relevant in this case. The spec is about parsing the AsciiDoc. Besides, it will still a long time before something comes out of that. But regardless, the output produced from AsciiDoc is designed to be flexible and does not limit what we can produce. The concern in Asciidoctor is compatibility with existing uses.

👍

**Comment by mojavelinux** [comment] 2020-03-02 21:15
> So, if someone is willing to financially support a "planned change" and someone is willing to work on it (ie. propose, discuss, design and implement a solution while respecting the constraints and compatibility goals) then I think it's fine no?

Yep, that's all I was stating. I just wanted to make sure that was the understanding, and it appears it is.

**Comment by mojavelinux** [comment] 2020-03-02 21:17
> but this "issue" is not limited to GitHub right?

It's limited to GitHub because GitHub is one place we have virtually no control over the styles. (Even GitLab has been flexible).

**Comment by mojavelinux** [comment] 2020-03-02 21:25
I don't want to try to backport semantics into the existing HTML converter. It's just a waste of resources, IMO. What I think we should do is create a semantic HTML converter that extends from the current HTML converter, then iteratively work on it until it's complete. At that point, we can make a stylesheet for it. Up until that time, it will be labeled as alpha, but it doesn't mean GitHub couldn't start using it right away.

(We can then think about how and when to make the semantic HTML converter the default).

**Comment by Mogztter** [comment] 2020-03-02 23:05
> I don't want to try to backport semantics into the existing HTML converter. It's just a waste of resources, IMO. What I think we should do is create a semantic HTML converter that extends from the current HTML converter, then iteratively work on it until it's complete

That's what I had in mind but with a mechanism to selectively enable the new semantic converter. Let's say, I want to use the new semantic converter but my extensions/stylesheets/whatever is tightly coupled with the current HTML structure produced by the HTML converter for images, so I want to enable the semantic converter on paragraphs and lists but I'm not ready yet to enable it on images. Does that makes sense? I thought about it because you said we should ensure a smooth transition... but maybe it's pointless 🤔 

> At that point, we can make a stylesheet for it. Up until that time, it will be labeled as alpha, but it doesn't mean GitHub couldn't start using it right away.
(We can then think about how and when to make the semantic HTML converter the default).

👍 

> It's limited to GitHub because GitHub is one place we have virtually no control over the styles. (Even GitLab has been flexible).

Ok fair enough.
Sorry about the digression on the semantic converter then 😉

**Comment by mojavelinux** [comment] 2020-03-03 00:25
> I want to enable the semantic converter on paragraphs and lists but I'm not ready yet to enable it on images. 

I think that's just asking for trouble / adding unnecessary complexity that will only serve to slow us down.

> I thought about it because you said we should ensure a smooth transition

My idea there is that replacing `<p>` with `<span>` might not

**Comment by mojavelinux** [comment] 2020-03-03 00:27
(Sorry, my touchpad went haywire and closed the issue. That was not my intention.)

**Comment by mojavelinux** [comment] 2020-03-03 00:34
> Do you need to remove the wrapping `<p>` element on items elements:

I think we've been able to demonstrate with other HTML-based converters that using `<span>` instead of `<p>` for the primary list text solves this problem well. The issue is not whether to make that change, it's how to roll out that change.

Clearly, I'm torn about whether or not it's appropriate to make this change in the current HTML converter. I worry a lot about compatibility, and that's why I put up resistance. But if users are nearly unanimous in wanting this change now, then I would listen to that and make the change before #242. Hopefully that explains my position better.

**Comment by wimdeblauwe** [comment] 2020-03-03 09:39
Can't we make this opt-in via either an attribute (like `:compact-lists: true`) or with a role:

```
[role="compact-lists"]
* Item 1
* Item 2 
```

**Comment by mojavelinux** [comment] 2020-03-03 09:55
That's mixing presentation with form. The heart of the matter is that the element should be a `<span>` with a CSS class, not a `<p>`. That way, you can more easily target it with styles. And the default display (kind of like an HTML document with no CSS) is consistent with the behavior of HTML itself.

**Comment by mojavelinux** [comment] 2020-03-03 09:57
In other words, this isn't really about compact lists vs non-compact lists. It's about the inappropriate use of the `<p>` element. The text definitely needs to be wrapped so it can be independently styled, but the `<p>` causes unnecessary space where CSS cannot be used (so you're starting with space instead of being able to use CSS to add space).

**Comment by wimdeblauwe** [comment] 2020-03-03 10:23
Ok, I agree. I am all for this change, but I do understand that current users might not like the change since there is an option that it will break their custom stylesheet. That is why I was thinking about ways to make it opt-in or opt-out until we have the semantic converter.

**Comment by muv1** [comment] 2020-04-18 22:07
Hi, I am the person who offered the bounty before. I just wanted to mention that
is still on the table, I am increasing offer to $1,000 if this is able to be
implemented.

Currently I am doing LaTeX to PDF, because I just couldnt find a good Markdown
to PDF solution. I saw that Kramdown has a PDF option via Prawn, but it seems to
be unmaintained. I would be interested to do Asciidoc to PDF, but I want the
option for Asciidoc to HTML as well, which means this issue is still a blocker
for me. Note I am serious about donating:

https://user-images.githubusercontent.com/61808913/79672377-eda03b00-8196-11ea-9d55-12257453f776.png

**Comment by mojavelinux** [comment] 2020-04-18 23:50
You can offer to pay someone to create a custom extension to suit your needs, but please don't float money to try to increase the priority of an issue for this project. That's not how OSS works.

In order for this issue to be resolves, or a PR even to be considered, this concern needs to be addressed:

> I'm torn about whether or not it's appropriate to make this change in the current HTML converter. I worry a lot about compatibility, and that's why I put up resistance. But if users are nearly unanimous in wanting this change now, then I would listen to that and make the change before #242. 

If you want an HTML converter that adheres closer to the semantics of HTML, including a fix for this particular issue, you may be interested in https://github.com/jirutka/asciidoctor-html5s. It's a preview of the new HTML converter that is proposed for this project in #242 (where we are discussing requirements).

**Comment by muv1** [comment] 2020-04-19 00:36
@mojavelinux thats interesting. This:

~~~
gem install asciidoctor-html5s
asciidoctor -b html5s -r asciidoctor-html5s a.adoc
~~~

Solves the issue posted here. If that was ever to land as the GitHub gem, the
issue would be totally solved. Probably the Gem has some issues I am not aware
of though. Hopefully one day it will be complete, as I think AsciiDoc can be a
strong alternative to Markdown. Though not in its current state.

Note I removed my previous comment, as you seem to disagree strongly with it.
But the offer still stands for any interested.

**Comment by mojavelinux** [comment] 2020-04-19 00:53
I'm glad to hear that gem addresses the issue. And thank you for respecting
my concern.

While I understand this issue is very important to certain users, and for
that reason something we do plan to address, I can assure you AsciiDoc is
already a very strong alternative to Markdown. AsciiDoc is being used by
many of the largest tech companies and projects in the world, and plenty
more small to medium ones  That doesn't mean it suits everyone's needs, of
course. But to say extra space between list items prevents AsciiDoc from
being successful and broadly adopted is disingenuous and simply not factual.

**Comment by tringuyen-yw** [comment] 2020-06-10 23:09
Would it be OK to add a new list option? Something like 

```
[compact-interline-spacing]
* Item1
* Item2
```

**Comment by kvegh** [comment] 2021-01-05 11:50
So, so far - if I get it right - no workaround around this yet?

**Comment by mojavelinux** [comment] 2021-01-05 12:11
The workaround / customization is to apply CSS. This is a display issue. It
has little to do with AsciiDoc itself.

**Comment by Frizlab** [comment] 2021-01-05 13:39
> So, so far - if I get it right - no workaround around this yet? 

For GitHub specifically, for Safari, I wrote a browser extension that implements, among other, a workaround for this (client-side). 
I don’t think there’ll be a workaround for asciidoc itself, as it’s mostly a CSS issue AFAICT.

https://github.com/Frizlab/My-Web-Quirks (`brew install --cask frizlab/perso/my-web-quirks`)

**Comment by 89z** [comment] 2021-01-05 14:43
@mojavelinux yeah, it does have to do with AsciiDoc. People can customize for their own sites, but AsciiDoc is also used for READMEs on GitHub itself. In that case, users cant customize and have to rely on the default styling. So defaults matter, and this issue itself is the reason why I have avoided AsciiDoc for several years.

**Comment by kvegh** [comment] 2021-01-05 15:28
That is my usecase too, we are using asciidoc on GitHub.
Appreciate the answer, in that case we'll look into markdown probably.

**Comment by Frizlab** [comment] 2021-01-05 17:43
FWIW I’ve opened an issue to the GitHub support team. I’ll keep you posted.

**Comment by 89z** [comment] 2021-01-05 17:47
@Frizlab please dont contact GitHub trying to push some browser extension. That is not the correct fix for this situation. The correct fix is not putting `<p>` element inside `<li>` elements by default. That can and should only be fixed at the package level. The issue is that the maintainers have no desire to do so.

**Comment by nfrankel** [comment] 2021-01-05 17:52
@89z If you're unhappy with a design decision of a product you're using for free, I've great news for you. Asciidoctor is Open Source. Nothing prevents you from forking it and making the changes you deem necessary.

**Comment by 89z** [comment] 2021-01-05 17:55
@nfrankel should I fork my own GitHub.com too? As the issue is with the Gem used on GitHub.com. The paragraph list issue cant be resolved on GitHub.com, until its resolved upstream, which is at the repo here: https://github.com/asciidoctor/asciidoctor, AKA the page we are currently on.

Me making these changes in a personal fork would be pointless, as GitHub website is not going to use my fork in their public facing website. Surely you know this?

**Comment by Frizlab** [comment] 2021-01-05 17:55
@89z Of course not…

The maintainers do not wish to remove the `<p>` from `<li>`, and that’s fine; I don’t really think they should either. The generator _is_ customizable though.

I simply asked GitHub to either tweak the CSS they generate (to simply remove padding for first `p` in `li` in generated) or tweak the generator options to avoid the `<p>` in `<li>`.
Both are relatively easy to do.

**Comment by 89z** [comment] 2021-01-05 17:59
@Frizlab nothing is wrong with the GitHub CSS. If you put a `<p>` element inside an `<li>` element, *its supposed to have a margin. Thats not an error. What is an error, is putting the `<p>` elements inside the `<li>` elements in the first place. I dont think the correct solution to the issue is to hack the HTML errors with CSS fixes.

**Comment by nfrankel** [comment] 2021-01-05 18:03
@89z I surely know nobody forces you to use GitHub or Asciidoctor. I surelly know that @mojavelinux already commented on the issue in detail. I surely know bad attitude when I see it.

**Comment by 89z** [comment] 2021-01-05 18:20
@nfrankel thanks for your valuable feedback!

**Comment by mojavelinux** [comment] 2021-01-05 19:16
Please stop this argument. It's off the rails, distracting, and not productive. I never said I wasn't going to implement the solution previously agreed on. I merely pointed out that this is a display issue. I stated that to emphasize that it's not something that is controlled by the AsciiDoc source, but rather by the output Asciidoctor produces and how that output is styled. That output can be controlled by CSS where CSS can be controlled.

GitHub happens to style `<p>` elements inside an `<li>` in a way that is outside of our control. We already know that. The only option for controlling the display on GitHub is to change the element used. This is not a shortcoming of the Asciidoctor processor. And it's neither correct nor incorrect to use a `<p>` element in this case. But we know that GitHub won't change its styles. So it's a reality we have to face. We're willing to make the change for the benefit of our users. I've already scheduled that change as indicated by the milestone. So further punching on Asciidoctor is not welcome and will only succeed in delaying a fix.

**Comment by Mogztter** [comment] 2021-02-09 12:06
If you are using [Refined GitHub](https://github.com/sindresorhus/refined-github) (if not, you should!), you can define the following styles to remove margins:

```css
.markdown-body li>p {
  margin-top: 0;
  margin-bottom: 0;
}
```

Open the extension options and copy-paste the above styles in the "Custom CSS" text area:

![custom-css](https://user-images.githubusercontent.com/333276/107360776-b0ff5080-6ad6-11eb-9b22-a7368ee35a1e.png)

And here's the result:

| Before | After |
|---|---|
| ![before](https://user-images.githubusercontent.com/333276/107360592-6f6ea580-6ad6-11eb-945f-8b98d1fd31e9.png) | ![result](https://user-images.githubusercontent.com/333276/107360613-75648680-6ad6-11eb-861e-35dd4200f927.png) |

https://github.com/opendevise/asciidoc-samples/blob/master/demo.adoc#1-first-steps-with-asciidoc

**Comment by sskras** [comment] 2021-05-08 16:05
Folks, a lot of comments here.

So, how can I achieve compact spacing for bulleted lists for any popular browser (without using the extension).
What's the consensus?

**Comment by toastal** [comment] 2021-11-16 14:44
> @sskras you can open a support ticket at https://support.github.com/. Hopefully, if enough people ask for this, they will do something.

I and others are waiting for the `<p> → <span>` migration. People use AsciiDoc on other Git forges (GitLab for instance renders it natively), and personal webpages. The current state as a paragraph does indeed feel like **bug** because _everyone_ needs to include a special stylesheet to deal with this issue. Hacking just GitHub does not solve the problem. Additionally screen readers have tools to skip paragraphs, but this content doesn't match the normal conception of a paragraph.

---

Personally, I'm working on a [Soupault](https://soupault.app/) plugin to clean up all of the issues I'm finding with AsciiDoc output. Currently this list includes: 

* [] paragraphing list items
* [x] strikethroughs using `<span>` instead of `<del>`
* [x] the entire body is listed as a the article when I want my article to be an `<article>` inside the bode.

Maybe I'll report back once it's more stable

**Comment by toastal** [comment] 2022-05-18 14:08
Reporting back tangentially...

https://git.sr.ht/~toastal/sourcehut-asciidoc-renderer

I've made a Nix script to help do READMEs or other docs in on Sourcehut. This script include stripping these extra `<p>`s on list items and tables because Sourcehut has similar issues with misrendering like GitHub (though it does still feel like a bug in Asciidoctor to begin with as many times list items don't need to be complex enough to contain paragraphs).

**Comment by mojavelinux** [comment] 2022-05-18 20:06
The question is not whether it is a bug. The output is the way it is because it was developed initially to be consistent with the output that AsciiDoc.py generated. Changing that structure years after the fact would affect every single user of Asciidoctor in some way, and I'm just not going to do that to this community. It's too late to change the markup in the existing built-in converter. That's why we are changing it in the new HTML converter. See #242.

**Comment by toastal** [comment] 2022-05-19 03:41
Ah, I did not consider that this would break AsciiDoc (:snake: version). This is a fair consideration and I don't disagree with plan. There are two problems though:

* It's often *not* the correct/semantic markup
* In embedded cases, there's not much anyone here can do to fix how the host is choosing to render that content. Sure this will always be the way and until broader adoption, platforms like GitHub will neglect this.

I subscribed to the #242 issue though. It will be cool to see what comes of it.

**Comment by 89z** [comment] 2022-09-10 13:33
Note that this quote from the original post:

> Markdown files render more compactly like this:
> 
> ~~~
>             <ul>
>                 <li>Item 1</li>
>                 <li>Item 2</li>
>                 <li>Item 3</li>
>             </ul>
> ~~~

is no longer correct. Using this Markdown on GitHub:

~~~
- one
- two
~~~

you get this result:

~~~html
<ul dir="auto">
   <li>
      <p dir="auto">one</p>
   </li>
   <li>
      <p dir="auto">two</p>
   </li>
</ul>
~~~

Note that the extra space is only on Readme pages an similar. Comments still seem to omit the extra space (for now).

**Comment by 89z** [comment] 2022-09-10 13:42
Note that with Markdown on GitHub, you can control the spacing. So this:

~~~
- one
- two
~~~

gets you this:

~~~html
<ul data-sourcepos="1:1-2:5" dir="auto">
   <li data-sourcepos="1:1-1:5">one</li>
   <li data-sourcepos="2:1-2:5">two</li>
</ul>
~~~

and this:

~~~
- one

- two
~~~

gets you this:

~~~html
<ul data-sourcepos="1:1-3:5" dir="auto">
   <li data-sourcepos="1:1-2:0">
      <p data-sourcepos="1:3-1:5" dir="auto">one</p>
   </li>
   <li data-sourcepos="3:1-3:5">
      <p data-sourcepos="3:3-3:5" dir="auto">two</p>
   </li>
</ul>
~~~

**Comment by mojavelinux** [comment] 2023-08-15 17:36
As I've already stated:

> That's why we are changing it in the new HTML converter.

Btw, you are free to add a compact role on the list, then modify the CSS accordingly. You have all the control you need to achieve the appearance you want. The main issue here is whether the principal text is wrapped in a paragraph by default. In the new HTML converter, it will not be. It will instead be wrapped in a span, making it easier to get compact by default with the option to add more space using targeted CSS.

**Closed by mojavelinux** 2023-08-15 17:36 UTC
Labels: github, improvement
