### ISSUE TITLE
A way to include all .adoc snippets into one .adoc file

### ISSUE THREAD

**Issue by chadmalla-ff** [asciidoctor/asciidoctor#3478] opened 2019-11-07 23:10 UTC
Hi I am using Spring Rest docs that uses asciidoctor. Is there any way to have all the generated `adoc` snippets that are generated into one `adoc` file glob-like. 

Example: 
`include::{snippets}/**/*adoc[]` 
Should recursively go through the subdirectories and get individual `adoc` and include them in one file. Basically I am trying to automate this process as much as possible. Please let me know if this is something that can be done in asciidoctor programmatically?

Thanks!

**Comment by mojavelinux** [comment] 2019-11-07 23:31
This is a duplicate of #855. I have explained there how this can be accomplished. It's best handled by an extension. See https://github.com/asciidoctor/asciidoctor/issues/855#issuecomment-551014591

**Closed by mojavelinux** 2019-11-07 23:31 UTC
Labels: duplicate
