### ISSUE TITLE
No id / title in images

### ISSUE THREAD

**Issue by Bastilla123** [asciidoctor/asciidoctor#4471] opened 2023-07-12 15:57 UTC
I set

image:testimage.png[title="Testtitle",id=newid]

I would expect that image get id="newid" in html source code and title are set in <src as title attribute> but i would expect that i get a title on bottom of image

I use asciidoc 2.0.20

**Comment by Bastilla123** [comment] 2023-07-12 16:02
image::storageterminal.png[title="Testtitle",id=newid] shows me id and title 
image:storageterminal.png[title="Testtitle",id=newid] not. Why can't inline image not?

**Comment by mojavelinux** [comment] 2023-07-13 10:19
This is a duplicate of #4311 and is already planned for the next minor of Asciidoctor.

The title is not passed through since it doesn't make any sense to have a block title on an inline element. (Note that the title attribute in HTML is something entirely different and not what the title attribute in AsciiDoc maps to).

What you can do is set the alt text for an image, whether it is block or inline.

```
image:storageterminal.png[Testtitle]
```

**Closed by mojavelinux** 2023-07-13 10:19 UTC

**Comment by mojavelinux** [comment] 2023-07-18 23:02
> The title is not passed through since it doesn't make any sense to have a block title on an inline element. 

Correction. The title attribute is passed through to the `title` attribute on the `<img>` tag in HTML.
