### ISSUE TITLE
note compatibility to markdown syntax to avoid confusion

### ISSUE THREAD

**Issue by gretel** [asciidoctor/asciidoctor#1447] opened 2015-07-28 20:26 UTC
https://github.com/asciidoctor/asciidoctor/blob/4345437dd4bfbb4087707d32ebecba485e71ed73/lib/asciidoctor.rb#L168 reads
```
    # Asciidoctor will recognize commonly-used Markdown syntax
    # to the degree it does not interfere with existing
    # AsciiDoc syntax and behavior.
```
i suggest adding that info to `README.md` :book: :eyeglasses: :pencil2: :computer:

**Comment by mojavelinux** [comment] 2015-07-29 04:07
This is covered in a few places in the user manual. See:

* http://asciidoctor.org/docs/user-manual/#sections
* http://asciidoctor.org/docs/user-manual/#markdown-style-horizontal-rules
* http://asciidoctor.org/docs/user-manual/#markdown-style-blockquotes

The compatibility basically amounts to section titles, block quotes, horizontal rules and some inline formatting. The inline formatting is mostly just coincidence / by design. The first three are intentional additions in Asciidoctor.

I agree it would be nice if there was one section in the user manual that covered all the compatibility. I think a separate issue in the asciidoctor.org repository (home to the user manual) should be filed with the goal of consolidating this information. (We're actually looking to remove most of the information from the README so it covers just the basics of getting started and pointers to the docs such as the user manual).

**Comment by mojavelinux** [comment] 2015-07-29 04:08
You emoji well :)

**Comment by gretel** [comment] 2015-07-29 13:41
thanks for pointing me at the relevant documentation :information_desk_person: :information_source: :books: :mortar_board: personally, i was just searching the page (`README.md`) for `markdown` and was like well, too bad it doesn't seem to be compatible. but for some fortunate reason i had another look at the code and figured..
having a feature list including `markdown` might be especially relevant in this omnipresent githubish context we are in here :smiling_imp: :bride_with_veil: :monkey: :monorail:

**Comment by mojavelinux** [comment] 2015-08-01 07:23
You might also find this section useful:

http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#markdown-compatibility-asciidoctor-only

I agree mentioning it more clearly in the intro is important. I've opened an issue to address it. See https://github.com/asciidoctor/asciidoctor.org/issues/409.

**Comment by mojavelinux** [comment] 2015-08-01 07:23
I'm going to close this issue as we'll handle it in the related issue.

**Comment by mojavelinux** [comment] 2015-08-01 07:24
> i suggest adding that info to README.md

You probably mean README.adoc :)

**Closed** 2015-08-01 07:23 UTC
