### ISSUE TITLE
Support capturing revision metadata from git repository

### ISSUE THREAD

**Issue by ilvetz** [asciidoctor/asciidoctor#2385] opened 2017-08-25 17:09 UTC
Now using bump scripts to include external files but it would be useful to captur author, revision number reading git commits.

Thinking to a git macro that set rev attributes

**Comment by mojavelinux** [comment] 2017-08-28 08:31
This sounds like a great idea for an extension! It's exactly this type of use case that the extension API was designed for.

**Comment by ilvetz** [comment] 2017-08-29 12:06
I would like to help but I don't know where to start

**Comment by Mogztter** [comment] 2017-08-29 15:41
@ilvetz You can have a look at the [extensions lab repository](https://github.com/asciidoctor/asciidoctor-extensions-lab).

**Comment by ilvetz** [comment] 2017-09-06 14:55
Thank you @Mogztter . 

I tried reading the documentation but I think that Asciidoctor does not support overwriting header attributes. I was thinking to a feature able to act like this:

```
:revnumber: gitinfo::tag[]
:revdate: gitinfo::committername[HEAD|tag]
```
but probably this is not a good design.

I do not get what would be the best pattern (PreProcessor, InlineMacroProcessor) ...

**Comment by Mogztter** [comment] 2017-09-06 16:14
Not sure if this is the best approach but you could use a `PreProcessor` to set attributes on the `document`: `gitinfo_tag`, `gitinfo_commit_date`, `gitinfo_committer_name`, etc...

Then use these attributes in your document:

```
:revnumber: {gitinfo_tag}
:revdate: {gitinfo_commit_date}
```

**Comment by danyill** [comment] 2017-09-22 05:01
@ilvetz I did something like @Mogztter suggested because I'm keen on this myself.

It's a bit of a hack but perhaps it's of some assistance: https://github.com/danyill/asciidoctor-extensions-lab/commit/1e2426d461adb4127c4cc2f855f571ed366ff722

I run this using a command like: `asciidoctor -r ./lib/git-metadata-preprocessor/extension.rb ./lib/git-metadata-preprocessor/sample.adoc  --trace`

_Disclaimer:_ I don't know much about (a) Asciidoctor, (b) Git or (c) Ruby.

The 'git' gem requires me to specify a path and requires the top-level path of the repository. It doesn't seem to offer a method to get this from an arbitrary point in the repo which would seem desirable. So I thought perhaps I could set an attribute in the document relative to the top of the repo but my attempts (see the commit) were unsuccessful so at the moment this is hard coded. Possibly this is because it's a preprocessor? I don't really understand the different processor types and how they work.

**Comment by mojavelinux** [comment] 2017-09-22 06:14
If you really want to do git right from Ruby, you need to use [rugged](https://rubygems.org/gems/rugged). That gem provides the Ruby bindings for libgit2. I've used it in several projects and while it requires understanding git a bit more, it's much more stable and reliable.

**Comment by mojavelinux** [comment] 2017-09-22 06:17
> It's a bit of a hack but perhaps it's of some assistance: danyill/asciidoctor-extensions-lab@1e2426d

This would make a nice addition to the upstream extension lab.

**Comment by mojavelinux** [comment] 2017-09-22 06:23
>  I thought perhaps I could set an attribute in the document relative to the top of the repo but my attempts (see the commit) were unsuccessful so at the moment this is hard coded. 

A preprocessor gets run before the document is parsed, so it can't see any attributes in the document.

One workaround is to parse the current document a second time in the preprocessor with the `:parse_header_only` option set. That way, you can peek into the header and read attributes from it. (You do have to be careful to pass all the same attributes or else things may go a bit differently).

I do this in the EPUB3 converter. See https://github.com/asciidoctor/asciidoctor-epub3/blob/master/lib/asciidoctor-epub3/spine_item_processor.rb#L23-L29

To make this simpler, there is a proposal to have the preprocessor deferred until after the header is parsed. See #2422.

**Comment by danyill** [comment] 2017-09-22 19:23
@mojavelinux Thanks for your help and suggestions, PR here https://github.com/asciidoctor/asciidoctor-extensions-lab/pull/79

**Comment by ilvetz** [comment] 2017-09-26 16:48
Wow! I'll try it asap. Thank you for your job @danyill

**Comment by mojavelinux** [comment] 2023-10-25 06:18
Closing as the git-metadata-preprocessor can now be found in the extensions lab. See https://github.com/asciidoctor/asciidoctor-extensions-lab

**Closed by mojavelinux** 2023-10-25 06:18 UTC
