### ISSUE TITLE
How to use various latex packages in latexmath sections

### ISSUE THREAD

**Issue by iwt-pjost** [asciidoctor/asciidoctor#4190] opened 2021-10-16 18:10 UTC
So I have sucessfully managed to write chemical equations using latexmath and the mhchem package like this:

```
= Using mhchem
:stem: latexmath

latexmath:[\require{mhchem}]
latexmath:[\ce{H2O}]
```

It renders fine in pdf, html and even in the vscode preview.

So I assumed I could do the same with the chemfig package.

```
= Using chemfig
:stem: latexmath

latexmath:[\require{chemfig}]
latexmath:[\chemfig{A<:B}]
```

That one however doesn't render. It just renders a "\chemfigA<:B".

Is there a way to include/import/refer latex packages in the latexmath sections? Even a hacky variant would be fine with me. I just can't think of any.

**Comment by mojavelinux** [comment] 2021-10-16 20:30
This is a duplicate of #953. See that issue for suggestions and workarounds.

**Closed by mojavelinux** 2021-10-16 20:30 UTC
