### ISSUE TITLE
Weird deprecation warning and NPE with converting to HTML

### ISSUE THREAD

**Issue by bbatsov** [asciidoctor/asciidoctor#3336] opened 2019-06-12 08:58 UTC
Suddenly today my CircleCI builds that were publishing pages like https://rubystyle.guide started failing like this https://circleci.com/gh/rubocop-hq/ruby-style-guide/78

I don't get the same problem locally with asciidoctor 2.0.10 and Ruby 2.6.2, and until today everything worked properly on CircleCI as well. Any idea what might be wrong?

**Comment by mojavelinux** [comment] 2019-06-12 09:03
A new version of Rouge was just released (see https://rubygems.org/gems/rouge). Either this is a bug in Rouge, or it's a bug in the integration with Rouge. I'll test really quick to see if it's on Asciidoctor's side.

**Comment by mojavelinux** [comment] 2019-06-12 09:08
Well, the warning is definitely a bug in Rouge. See this line: https://github.com/rouge-ruby/rouge/blob/6d62ba17dd50cc7dbc94c59c753c82c13a48db6d/lib/rouge/lexer.rb#L421-L424

**Comment by bbatsov** [comment] 2019-06-12 10:05
You're the best project maintainer ever! Thanks for the fast response!

**Comment by mojavelinux** [comment] 2019-06-12 10:14
Thanks! :blush: 

Sure enough, this is the source of our woes. https://github.com/rouge-ruby/rouge/issues/1175

Rouge 3.4.0 is, for all intents and purposes, a bad release. I would recommend locking to 3.3.0 until a patch release is available. I submitted a fix upstream, so we'll track that with this issue.

**Comment by mojavelinux** [comment] 2019-06-12 11:37
It turns out I can fix this in Asciidoctor. We are using a deprecated API. If we switch to the one which is not deprecated, we still support all the same versions of Rouge, but we won't have this issue. I also see some other things to fix, so I'll go ahead and schedule this for 2.0.11 (independent of what happens in Rouge).

**Comment by mojavelinux** [comment] 2019-06-12 11:38
We'll need the same fix in Asciidoctor PDF as well.

**Comment by ashmaroli** [comment] 2019-06-12 13:20
> Rouge 3.4.0 is, for all intents and purposes, a bad release.

@mojavelinux Why is Rouge 3.4.0 bad **for all intents and purposes**..? If the API changes around `:continue` were to be reverted, what else had been a bad change?

**Comment by mojavelinux** [comment] 2019-06-12 16:44
My use of a figure of speech perhaps made this point come across overstated.

Any application that invokes the Lexer.lex API with an options hash (even if that hash is empty) will always warn and, for certain snippets, will also crash. Asciidoctor is one of these applications. (I've seen the failure for mixed HTML+JavaScript and YAML).

There was no indication prior to 3.4.0 that this was a deprecated API. So we jumped from an API which was working perfectly fine to one that was no longer reliable in a minor release. As a result, I'm going to be fielding issue reports like this one until the situation is resolved.

I made a definitive statement to give Asciidoctor users a fair warning that they will likely encounter problems using the 3.4.0 release. Hopefully, that helps you understand what I meant.

**Comment by ashmaroli** [comment] 2019-06-12 16:50
> Hopefully, that helps you understand what I meant.

Yes Dan, I understand your point regarding the *breaking-semver* principle. If its Asciidoctor for you, its Jekyll for me. My intention was to assess what other changes in Rouge 3.4 needed to be reverted for it to be acceptable to you..

**Comment by mojavelinux** [comment] 2019-06-12 17:21
> My intention was to assess what other changes in Rouge 3.4 needed to be reverted for it to be acceptable to you..

Everything else seems fine according to my tests. (Though fixing the source code warnings would be ideal).

> I understand your point regarding the breaking-semver principle.

It's more than that. Using Rouge 3.4.0 with Asciidoctor right now will almost certainly lead to the processor crashing on certain documents. So yes, it's about semver, but it's also about breaking builds.

**Comment by pyrmont** [comment] 2019-06-12 20:26
I've been in contact with @mojavelinux directly but just wanted to say sorry to @bbatsov for the error. The problematic behaviour has been reverted and a new release (v3.4.1) pushed to RubyGems. Not quite the start I was hoping for after Rouge awoke from its slumber :(

**Comment by mojavelinux** [comment] 2019-06-12 21:13
How's the saying go? There's no such thing as bad publicity.

I'm still going to update Asciidoctor to move away from this API since it's now considered deprecated.

**Comment by mojavelinux** [comment] 2019-06-12 21:13
Oh, and thanks for the patch release @pyrmont!

**Comment by mojavelinux** [comment] 2019-06-12 21:17
I can confirm that 3.4.1 works without any warnings (unless I have warnings enabled).

**Comment by pyrmont** [comment] 2019-06-12 23:30
Thanks for taking the time to go through different fixes, @mojavelinux. It was very helpful! :)

**Comment by jneen** [comment] 2019-06-13 03:17
For the record, I don't believe arbitrary options passed to the `Lexer#lex` method have ever been supported. It may have once been the case that `Lexer.find_fancy` could return a class, and the static method could be called with options, but that has not been the case for many versions now (certainly since 3.0 at least).

**Comment by mojavelinux** [comment] 2019-06-13 04:20
The options at least gave the illusion of being passed, even if they came in too late to be effective. See https://github.com/rouge-ruby/rouge/blob/v3.3.0/lib/rouge/lexer.rb#L396-L397

I think that impression took hold because it's how it works in Pygments. You resolve the lexer, then pass it options.

I fully acknowledge at this point that Asciidoctor is not using the preferred API and needs to be updated.

**Comment by mojavelinux** [comment] 2019-06-13 04:21
It seems like the solution is as simple as passing `{ start_inline: true }` to `find_fancy`. But we don't know what the lexer is until we call `find_fancy`, so it's a chicken-egg problem. However, once the lexer is resolved, we can then turn around and pass options to the lexer constructor. I'm preparing a patch that does this.

Either way, the lexer options must be passed to the constructor, not to the `#lex` method.

**Comment by mojavelinux** [comment] 2019-06-13 04:32
I can confirm that the `start_inline` lexer option was never doing anything the way we were passing it, but it's tempered by the fact that Rouge already guesses right in most cases. I figured out a case when I can make it guess wrong and I will add that as a test in Asciidoctor.

**Comment by mojavelinux** [comment] 2019-06-13 04:34
Thanks for all the input!

**Comment by mojavelinux** [comment] 2019-06-13 10:33
I've submitted a patch to pass options to the Rouge lexer correctly.

However, I discovered that 3.4.1 introduces a different problem (which is only seen when Ruby's verbose mode is enabled). Once this patch is merged and the next version of Asciidoctor is released, you can use Rouge 3.4.0 again, but Rouge 3.4.1 will give you a warning not caused by Asciidoctor. Hopefully by then Rouge 3.4.2 will be out, and we'll be back to a stable situation.

**Comment by mojavelinux** [comment] 2019-06-13 21:01
The issue with 3.4.1 has been reported here: https://github.com/rouge-ruby/rouge/issues/1186

**Comment by mojavelinux** [comment] 2019-06-13 21:06
I now understand how I got myself twisted in knots over this. When we were using Lexers.find, it returned the Lexer class. The Lexer.lex method then passes options to the Lexer constructor, which is a supported use case. But when we switched to using Lexers.find_fancy, that returns a Lexer instance. The options argument for Lexer#lex is completely different and really reserved for an internal option only.

The fact that Lexers.find and Lexers.find_fancy gives you a different type of object (the first is a class, the second is an instance), but both respond to "lex", is what led Asciidoctor astray in the call chain.

The simplest solution, which the pending PR implements, is to avoid passing options to the lex method and instead pass them to the Lexer constructor directly. (The alternative would be to pass options to find_fancy, but we don't know what options we need until we have the Lexer).

**Comment by mojavelinux** [comment] 2019-06-14 00:28
Now that I understand the mistake that I made, I have no problem with not passing options to Lexer#lex. In fact, it makes sense. The lexer is already initialized, so passing options to configure it at that point is too late (and was never a supported contract).

(I just got thrown for a loop because there's both a static and instance method with the same signature, and I assumed the options hash was handled the same in both cases).

**Comment by mojavelinux** [comment] 2019-06-14 05:52
After reviewing Asciidoctor PDF, I discovered that it isn't affected by this change in Rouge since it was using Lexer.lex (instead of Lexer#lex). For reasons already cited, it's fine to pass options to Lexer.lex because they get passed to the Lexer constructor. So it was really just Asciidoctor core that was using the wrong logic.

**Closed** 2019-06-15 06:26 UTC
Labels: bug, tracking, v2.0.11
